(()=>{
  const allowed=['OWNER','CEO','ADMISSION','ADMISSIONS_REVIEWER','ADMISSIONS_APPROVER'];
  Object.assign(pages,{admissions:'التقديم والقبول'});
  allowed.forEach(r=>{access[r]||(access[r]=[]);if(!access[r].includes('admissions'))access[r].push('admissions')});
  const oldRenderAdmissions=render;
  const labels={DRAFT:'مسودة',SUBMITTED:'مُرسل',DOCUMENTS_REVIEW:'مراجعة المستندات',ASSESSMENT_SCHEDULED:'موعد تقييم',ASSESSED:'تم التقييم',WAITING_LIST:'قائمة انتظار',ACCEPTED:'مقبول',REJECTED:'مرفوض',ENROLLED:'تم القيد',WITHDRAWN:'منسحب'};
  const rows=a=>(a||[]).map(x=>'<tr onclick="openAdmission(\''+x.id+'\')"><td>'+esc(x.application_number)+'</td><td>'+esc(x.student_name)+'</td><td>'+esc(x.requested_grade)+'</td><td>'+esc(x.division)+'</td><td>'+esc(x.academic_year)+'</td><td>'+esc(labels[x.status]||x.status)+'</td><td>'+esc(x.primary_phone)+'</td></tr>').join('')||'<tr><td colspan="7">لا توجد طلبات تقديم.</td></tr>';
  async function admissionsPage(){
    if(!allowed.includes(profile.role))return $('#content').innerHTML='<div class="msg err">غير مصرح.</div>';
    const r=await supabase.from('admission_applications').select('*').order('created_at',{ascending:false}).range(0,999);
    if(r.error)throw r.error;window._admissions=r.data||[];
    $('#content').innerHTML='<div class="grid cards">'+metric('إجمالي المتقدمين',n(r.data.length),'حسب صلاحيتك')+metric('بانتظار المراجعة',n(r.data.filter(x=>['SUBMITTED','DOCUMENTS_REVIEW'].includes(x.status)).length),'')+metric('المقبولون',n(r.data.filter(x=>x.status==='ACCEPTED').length),'','green')+metric('تم القيد',n(r.data.filter(x=>x.status==='ENROLLED').length),'لا تُنشأ رسوم تلقائيًا','green')+'</div><div class="sec"><h3>التقديم والقبول</h3><div class="tools"><input id="admissionSearch" placeholder="بحث بالرقم أو الاسم أو الهاتف أو الصف" oninput="filterAdmissions()">'+(['OWNER','ADMISSION'].includes(profile.role)?'<button class="btn primary" onclick="newAdmission()">+ طلب تقديم</button>':'')+'</div></div><div class="tablewrap"><table id="admissionsTable" class="tbl"><thead><tr><th>رقم الطلب</th><th>الطالب</th><th>الصف</th><th>القسم</th><th>السنة</th><th>الحالة</th><th>الهاتف</th></tr></thead><tbody id="admissionsBody">'+rows(r.data)+'</tbody></table></div>';
  }
  window.filterAdmissions=()=>{const q=($('#admissionSearch')?.value||'').toLocaleLowerCase('ar');$('#admissionsBody').innerHTML=rows((window._admissions||[]).filter(x=>!q||[x.application_number,x.student_name,x.primary_phone,x.requested_grade,x.academic_year].some(v=>String(v||'').toLocaleLowerCase('ar').includes(q))))};
  window.newAdmission=()=>openM('طلب تقديم جديد','<form id="admissionForm"><div class="split"><div class="f"><label>اسم الطالب</label><input id="aaName" required></div><div class="f"><label>تاريخ الميلاد</label><input id="aaBirth" type="date" required></div></div><div class="split"><div class="f"><label>الرقم القومي</label><input id="aaNational"></div><div class="f"><label>جواز السفر</label><input id="aaPassport"></div></div><div class="split"><div class="f"><label>الصف المطلوب</label><input id="aaGrade" required></div><div class="f"><label>القسم</label><select id="aaDivision"><option value="AMERICAN">American</option><option value="BRITISH">British</option></select></div></div><div class="split"><div class="f"><label>السنة الدراسية</label><input id="aaYear" placeholder="2026-2027" required></div><div class="f"><label>الهاتف الأساسي</label><input id="aaPhone" required></div></div><div class="split"><div class="f"><label>البريد</label><input id="aaEmail" type="email"></div><div class="f"><label>الجنسية</label><input id="aaNationality"></div></div><div class="f"><label>المدرسة السابقة</label><input id="aaPrevious"></div><div class="f"><label>العنوان</label><textarea id="aaAddress"></textarea></div><div class="note">يُحفظ كمسودة ولا ينشئ طالبًا أو رسومًا مالية.</div><button class="btn primary w">حفظ المسودة</button></form>');
  document.addEventListener('submit',async e=>{if(e.target.id!=='admissionForm')return;e.preventDefault();if(!$('#aaNational').value.trim()&&!$('#aaPassport').value.trim())return uiToast('أدخل الرقم القومي أو جواز السفر.','error');const r=await supabase.from('admission_applications').insert({academic_year:$('#aaYear').value.trim(),requested_grade:$('#aaGrade').value.trim(),division:$('#aaDivision').value,student_name:$('#aaName').value.trim(),birth_date:$('#aaBirth').value,nationality:$('#aaNationality').value.trim()||null,national_id:$('#aaNational').value.trim()||null,passport_number:$('#aaPassport').value.trim()||null,previous_school:$('#aaPrevious').value.trim()||null,primary_phone:$('#aaPhone').value.trim(),email:$('#aaEmail').value.trim()||null,address:$('#aaAddress').value.trim()||null,created_by:session.user.id,updated_by:session.user.id}).select().single();if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم حفظ طلب التقديم كمسودة.','success');await admissionsPage()});
  const nextActions=x=>{const r=profile.role,h=[];if(x.status==='DRAFT'&&['ADMISSION','OWNER'].includes(r))h.push(['SUBMITTED','إرسال']);if(x.status==='SUBMITTED'&&['ADMISSIONS_REVIEWER','OWNER'].includes(r))h.push(['DOCUMENTS_REVIEW','بدء مراجعة المستندات']);if(x.status==='DOCUMENTS_REVIEW'&&['ADMISSIONS_REVIEWER','OWNER'].includes(r))h.push(['ASSESSMENT_SCHEDULED','تحديد التقييم']);if(x.status==='ASSESSMENT_SCHEDULED'&&['ADMISSIONS_REVIEWER','OWNER'].includes(r))h.push(['ASSESSED','إتمام التقييم']);if(x.status==='ASSESSED'&&['ADMISSIONS_APPROVER','OWNER'].includes(r)){h.push(['ACCEPTED','قبول']);h.push(['WAITING_LIST','انتظار']);h.push(['REJECTED','رفض'])}return h};
  window.openAdmission=id=>{const x=(window._admissions||[]).find(v=>v.id===id);if(!x)return;const actions=nextActions(x).map(a=>'<button class="btn '+(a[0]==='ACCEPTED'?'ok':'ghost')+'" onclick="admissionTransition(\''+x.id+'\',\''+a[0]+'\')">'+a[1]+'</button>').join('');openM('ملف طلب التقديم','<div class="receipt-grid"><div><strong>الرقم:</strong> '+esc(x.application_number)+'</div><div><strong>الطالب:</strong> '+esc(x.student_name)+'</div><div><strong>الصف:</strong> '+esc(x.requested_grade)+'</div><div><strong>القسم:</strong> '+esc(x.division)+'</div><div><strong>الحالة:</strong> '+esc(labels[x.status]||x.status)+'</div><div><strong>المستندات:</strong> '+esc(x.document_status)+'</div><div><strong>الهاتف:</strong> '+esc(x.primary_phone)+'</div><div><strong>البريد:</strong> '+esc(x.email||'—')+'</div></div><div class="tools" style="margin-top:14px">'+actions+(x.status==='ACCEPTED'&&['ADMISSIONS_APPROVER','OWNER'].includes(profile.role)?'<button class="btn primary" onclick="enrollAdmission(\''+x.id+'\')">إنشاء ملف الطالب</button>':'')+'<button class="btn ghost" onclick="printAdmission(\''+x.id+'\')">طباعة</button></div><div class="note">إنشاء ملف الطالب يتم ذريًا وبأرصدة صفرية؛ الرسوم تحتاج خطة معتمدة منفصلة.</div>')};
  window.admissionTransition=async(id,to)=>{let reason=null;if(['WAITING_LIST','REJECTED','WITHDRAWN'].includes(to)){openM('سبب القرار','<form id="admissionReason"><input id="arId" type="hidden" value="'+esc(id)+'"><input id="arTo" type="hidden" value="'+esc(to)+'"><div class="f"><label>السبب الإلزامي</label><textarea id="arReason" minlength="3" required></textarea></div><button class="btn primary w">تأكيد</button></form>');return}const r=await supabase.rpc('transition_admission',{p_application:id,p_to:to,p_reason:null});if(r.error)return uiToast(r.error.message,'error',8000);closeM();await admissionsPage()};
  document.addEventListener('submit',async e=>{if(e.target.id!=='admissionReason')return;e.preventDefault();const r=await supabase.rpc('transition_admission',{p_application:$('#arId').value,p_to:$('#arTo').value,p_reason:$('#arReason').value.trim()});if(r.error)return uiToast(r.error.message,'error',8000);closeM();await admissionsPage()});
  window.enrollAdmission=async id=>{const r=await supabase.rpc('enroll_admission_application',{p_application:id,p_idempotency_key:crypto.randomUUID()});if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم إنشاء ملف الطالب وحسابه بأرصدة صفرية.','success');await admissionsPage()};
  window.printAdmission=id=>{const x=(window._admissions||[]).find(v=>v.id===id);if(!x)return;const host=$('#printArea');host.innerHTML='<div class="print-report"><header><h1>Bradford School ERP</h1><h2>ملف طلب تقديم</h2></header><div class="receipt-grid"><div>رقم الطلب: '+esc(x.application_number)+'</div><div>الطالب: '+esc(x.student_name)+'</div><div>الصف: '+esc(x.requested_grade)+'</div><div>القسم: '+esc(x.division)+'</div><div>السنة: '+esc(x.academic_year)+'</div><div>الحالة: '+esc(labels[x.status]||x.status)+'</div></div></div>';host.classList.remove('print-only');window.print();setTimeout(()=>{host.innerHTML='';host.classList.add('print-only')},300)};
  render=async function(){if(page==='admissions')return admissionsPage();return oldRenderAdmissions()};
})();
