(()=>{
 const roles=['OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT','TREASURY','AUDITOR'];Object.assign(pages,{cheques:'الشيكات'});roles.forEach(r=>{access[r]||(access[r]=[]);if(!access[r].includes('cheques'))access[r].push('cheques')});
 const oldRenderAC=render,all=async(t,s='*',o='created_at')=>{const r=await supabase.from(t).select(s).order(o,{ascending:false}).range(0,999);if(r.error)throw r.error;return r.data||[]};
 async function assetsFull(){const [a,m,w,c,d,tr]=await Promise.all([all('v_asset_book_values','*','purchase_date'),all('asset_maintenance'),all('asset_warranties'),all('asset_inventory_counts'),all('asset_disposals'),all('asset_transfers')]);window._assetsFull={assets:a,maintenance:m,warranties:w,counts:c,disposals:d,transfers:tr};const value=a.reduce((s,x)=>s+Number(x.book_value_piasters||0),0),missing=a.filter(x=>x.asset_status==='MISSING').length,exp=w.filter(x=>x.end_date&&new Date(x.end_date)<=new Date(Date.now()+30*86400000)).length;$('#content').innerHTML='<div class="grid cards">'+metric('الأصول',n(a.length),'')+metric('القيمة الدفترية',egp(value),'')+metric('أصول مفقودة',n(missing),'','red')+metric('ضمانات تنتهي خلال 30 يومًا',n(exp),'','amber')+'</div><div class="sec"><h3>دورة حياة الأصول</h3><input id="assetSearchFull" placeholder="بحث بالكود أو الاسم أو الموقع" oninput="filterAssetsFull()"></div><div class="tools"><button class="btn ghost" onclick="printTable()">طباعة / PDF</button><button class="btn ghost" onclick="downloadTableCSV()">CSV / Excel</button></div><div class="tablewrap"><table id="assetFullTable" class="tbl"><thead><tr><th>الكود</th><th>الأصل</th><th>الفئة</th><th>الموقع</th><th>التكلفة</th><th>الإهلاك المتراكم</th><th>القيمة الدفترية</th><th>الحالة</th></tr></thead><tbody id="assetFullBody">'+assetRows(a)+'</tbody></table></div>'}
 const assetRows=a=>(a||[]).map(x=>'<tr onclick="openAssetLifecycle(\''+x.id+'\')"><td>'+esc(x.asset_code||'—')+'</td><td>'+esc(x.asset_name)+'</td><td>'+esc(x.category||'—')+'</td><td>'+esc(x.location||'—')+'</td><td>'+egp(x.acquisition_cost_piasters)+'</td><td>'+egp(x.accumulated_depreciation_piasters)+'</td><td>'+egp(x.book_value_piasters)+'</td><td>'+esc(x.asset_status)+'</td></tr>').join('')||'<tr><td colspan="8">لا توجد أصول.</td></tr>';
 window.filterAssetsFull=()=>{const q=($('#assetSearchFull')?.value||'').toLocaleLowerCase('ar');$('#assetFullBody').innerHTML=assetRows(window._assetsFull.assets.filter(x=>!q||[x.asset_code,x.asset_name,x.category,x.location].some(v=>String(v||'').toLocaleLowerCase('ar').includes(q))))};
 window.openAssetLifecycle=async id=>{const a=window._assetsFull.assets.find(x=>x.id===id),[e,m,w,t]=await Promise.all([all('asset_lifecycle_events','*','created_at').then(x=>x.filter(v=>v.asset_id===id)),Promise.resolve(window._assetsFull.maintenance.filter(x=>x.asset_id===id)),Promise.resolve(window._assetsFull.warranties.filter(x=>x.asset_id===id)),Promise.resolve(window._assetsFull.transfers.filter(x=>x.asset_id===id))]);openM('بطاقة الأصل','<div class="receipt-grid"><div>الكود: '+esc(a.asset_code||'—')+'</div><div>الأصل: '+esc(a.asset_name)+'</div><div>الموقع: '+esc(a.location||'—')+'</div><div>القيمة الدفترية: '+egp(a.book_value_piasters)+'</div><div>العمر: '+esc(a.useful_life_months||'—')+' شهر</div><div>الإهلاك الشهري: '+egp(a.monthly_depreciation_piasters)+'</div></div><h3>السجل التاريخي</h3><div class="tablewrap"><table class="tbl"><tbody>'+(e.map(x=>'<tr><td>'+esc(x.event_date)+'</td><td>'+esc(x.event_type)+'</td><td>'+esc(x.reason||'—')+'</td></tr>').join('')||'<tr><td>لا يوجد سجل.</td></tr>')+'</tbody></table></div><div class="note">الصيانة: '+n(m.length)+' | الضمانات: '+n(w.length)+' | النقل والعهد: '+n(t.length)+'</div><button class="btn ghost" onclick="printAssetCard(\''+id+'\')">طباعة بطاقة الأصل</button>')};
 window.printAssetCard=id=>{const a=window._assetsFull.assets.find(x=>x.id===id),h=$('#printArea');h.innerHTML='<div class="print-report"><header><h1>Bradford School ERP</h1><h2>بطاقة أصل</h2></header><div class="receipt-grid"><div>الكود: '+esc(a.asset_code||'—')+'</div><div>الأصل: '+esc(a.asset_name)+'</div><div>الموقع: '+esc(a.location||'—')+'</div><div>التكلفة: '+egp(a.acquisition_cost_piasters)+'</div><div>الإهلاك: '+egp(a.accumulated_depreciation_piasters)+'</div><div>القيمة الدفترية: '+egp(a.book_value_piasters)+'</div></div></div>';h.classList.remove('print-only');window.print();setTimeout(()=>{h.innerHTML='';h.classList.add('print-only')},300)};
 async function chequesPage(){const a=await all('v_cheque_due_alerts','*','due_date');window._cheques=a;const due=a.filter(x=>x.alert_status==='DUE_SOON').length,over=a.filter(x=>x.alert_status==='OVERDUE').length;$('#content').innerHTML='<div class="grid cards">'+metric('الشيكات',n(a.length),'')+metric('تستحق خلال 7 أيام',n(due),'','amber')+metric('متأخرة',n(over),'','red')+metric('محصلة',n(a.filter(x=>x.status==='CLEARED').length),'','green')+'</div><div class="sec"><h3>الشيكات الواردة والصادرة</h3><input id="chequeSearch" placeholder="بحث بالرقم أو البنك أو الطرف" oninput="filterCheques()"></div><div class="tools"><button class="btn ghost" onclick="printTable()">طباعة / PDF</button><button class="btn ghost" onclick="downloadTableCSV()">CSV / Excel</button></div><div class="tablewrap"><table id="chequeTable" class="tbl"><thead><tr><th>الرقم</th><th>الاتجاه</th><th>الطرف</th><th>المبلغ</th><th>الإصدار</th><th>الاستحقاق</th><th>الحالة</th><th>التنبيه</th></tr></thead><tbody id="chequeBody">'+chequeRows(a)+'</tbody></table></div>'}
 const chequeRows=a=>(a||[]).map(x=>'<tr onclick="openCheque(\''+x.id+'\')"><td>'+esc(x.cheque_number)+'</td><td>'+esc(x.direction)+'</td><td>'+esc(x.beneficiary||'—')+'</td><td>'+egp(x.amount_piasters)+'</td><td>'+esc(x.issue_date)+'</td><td>'+esc(x.due_date||'—')+'</td><td>'+pill(x.status)+'</td><td>'+esc(x.alert_status)+'</td></tr>').join('')||'<tr><td colspan="8">لا توجد شيكات.</td></tr>';
 window.filterCheques=()=>{const q=($('#chequeSearch')?.value||'').toLowerCase();$('#chequeBody').innerHTML=chequeRows(window._cheques.filter(x=>!q||[x.cheque_number,x.beneficiary,x.direction,x.status].some(v=>String(v||'').toLowerCase().includes(q))))};
 window.openCheque=async id=>{const x=window._cheques.find(v=>v.id===id),r=await supabase.from('cheque_status_history').select('*').eq('cheque_id',id).order('changed_at',{ascending:false});let actions='';if(x.status==='OUTSTANDING'&&['OWNER','FINANCE_MANAGER','TREASURY'].includes(profile.role))actions='<button class="btn danger" onclick="chequeReason(\''+id+'\',\'cancel_cheque\')">إلغاء موثق</button> <button class="btn warn" onclick="chequeReason(\''+id+'\',\'bounce_cheque\')">مرتجع</button>';openM('تفاصيل الشيك','<pre style="white-space:pre-wrap;direction:rtl">'+esc(JSON.stringify(x,null,2))+'</pre><h3>سجل الحالات</h3><div class="tablewrap"><table class="tbl"><tbody>'+((r.data||[]).map(v=>'<tr><td>'+esc(new Date(v.changed_at).toLocaleString('ar-EG'))+'</td><td>'+esc(v.from_status||'—')+' ← '+esc(v.to_status)+'</td><td>'+esc(v.reason||'—')+'</td></tr>').join('')||'<tr><td>لا يوجد سجل.</td></tr>')+'</tbody></table></div><div class="tools">'+actions+'</div>')};
 window.chequeReason=(id,fn)=>openM('سبب الإجراء','<form id="chequeReasonForm"><input id="crId" type="hidden" value="'+esc(id)+'"><input id="crFn" type="hidden" value="'+esc(fn)+'"><div class="f"><label>السبب الإلزامي</label><textarea id="crReason" minlength="3" required></textarea></div><button class="btn primary w">تأكيد</button></form>');document.addEventListener('submit',async e=>{if(e.target.id!=='chequeReasonForm')return;e.preventDefault();const fn=$('#crFn').value,p={p_cheque_id:$('#crId').value,p_reason:$('#crReason').value.trim()},r=await supabase.rpc(fn,p);if(r.error)return uiToast(r.error.message,'error',8000);closeM();await chequesPage()});
 render=async function(){if(page==='assets')return assetsFull();if(page==='cheques')return chequesPage();return oldRenderAC()};
})();
