(()=>{
 const canPrepare=()=>['OWNER','FINANCE_MANAGER','IG_ACCOUNTANT'].includes(profile?.role);
 const isApprover=()=>profile?.role==='DR_AMANY_APPROVER';
 const labels={OL:'OL',AS:'AS',A2:'A2',FULL_A_LEVEL:'Full A Level',FIRST_ENTRY:'First Entry',RETAKE:'Retake',REMARK:'Remark',LATE_ENTRY:'Late Entry'};
 let rows=[];
 const tr=x=>'<tr class="'+(x.status==='POSTED'?'bfApprovedByAmany':'bfPendingApproval')+'" onclick="igExamDetail(\''+x.id+'\')"><td>'+esc(x.awarding_body)+'</td><td>'+esc(x.subject_code)+'</td><td>'+esc(x.subject_name)+'</td><td>'+esc(labels[x.level]||x.level)+'</td><td>'+esc(x.session_code)+'</td><td>'+esc(labels[x.entry_type]||x.entry_type)+'</td><td>'+egp(x.fee_piasters)+'</td><td>'+egp(x.paid_piasters)+'</td><td>'+egp(x.remaining_piasters)+'</td><td>'+pill(x.status)+'</td><td onclick="event.stopPropagation()">'+(x.status==='DRAFT'&&canPrepare()?'<button class="btn ghost" onclick="submitIGExam(\''+x.id+'\')">إرسال</button> ':'')+(x.status==='SUBMITTED'&&isApprover()?'<button class="btn ok" onclick="reviewIGExam(\''+x.id+'\',\'APPROVE\')">اعتماد</button> <button class="btn danger" onclick="reviewIGExamDialog(\''+x.id+'\')">رفض</button> ':'')+(x.status==='POSTED'&&Number(x.remaining_piasters)>0&&canPrepare()?'<button class="btn primary" onclick="newIGExamReceipt(\''+x.account_id+'\')">تحصيل</button>':'—')+'</td></tr>';
 async function load(){const r=await supabase.from('v_ig_exam_entry_balances').select('*').order('created_at',{ascending:false});if(r.error){if(/does not exist|schema cache/i.test(r.error.message||''))return {pending:true,error:r.error};throw r.error}rows=r.data||[];return {pending:false}}
 window.appendIGExamFees=async()=>{const host=$('#content');if(!host)return;const state=await load();if(state.pending){host.insertAdjacentHTML('beforeend','<div class="note orange" style="margin-top:14px"><strong>رسوم مواد IG:</strong> Migration جاهزة للمراجعة والتطبيق بعد إثبات Backup وStaging؛ لم تُطبّق على Production من الواجهة.</div>');return}host.insertAdjacentHTML('beforeend','<div class="sec"><h3>رسوم مواد IG المنفصلة</h3><div class="tools"><input id="igExamSearch" placeholder="المادة أو الكود أو الجهة أو Session" oninput="filterIGExams()">'+(canPrepare()?'<button class="btn primary" onclick="newIGExamEntry()">+ إضافة رسم مادة</button><button class="btn ghost" onclick="newIGExamReceipt()">تحصيل متعدد المواد</button>':'')+'<button class="btn ghost" onclick="printCurrentTable()">طباعة / PDF</button><button class="btn ghost" onclick="downloadCurrentTableCSV()">CSV / Excel</button></div></div><div id="igExamTable">'+table(rows)+'</div><div class="note" style="margin-top:10px">رسوم المدرسة مستقلة عن رسوم مواد IG. لا يدخل DRAFT أو SUBMITTED في المدفوع؛ التجميع يعتمد على بنود التحصيل POSTED فقط.</div>')};
 function table(a){return '<div class="tablewrap"><table class="tbl"><thead><tr><th>الجهة</th><th>الكود</th><th>المادة</th><th>المستوى</th><th>Session</th><th>نوع القيد</th><th>الرسوم</th><th>المدفوع المعتمد</th><th>المتبقي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>'+((a||[]).map(tr).join('')||'<tr><td colspan="11" class="empty">لا توجد رسوم مواد IG مسجلة.</td></tr>')+'</tbody></table></div>'}
 window.filterIGExams=()=>{const q=($('#igExamSearch')?.value||'').toLocaleLowerCase('ar');$('#igExamTable').innerHTML=table(rows.filter(x=>[x.awarding_body,x.subject_code,x.subject_name,x.session_code,x.level,x.entry_type,x.status].some(v=>String(v||'').toLocaleLowerCase('ar').includes(q))))};
 const accountOptions=()=>((window._igAccounts||[]).map(a=>'<option value="'+a.id+'">'+esc((a.student_code||'')+' — '+(a.student_name||''))+'</option>').join(''));
 window.newIGExamEntry=()=>openM('إضافة رسم مادة IG','<form id="igExamEntryForm"><div class="f"><label>الطالب</label><select id="igeAccount" required>'+accountOptions()+'</select></div><div class="split"><div class="f"><label>الجهة</label><input id="igeBody" required maxlength="80" placeholder="Cambridge / Pearson / OxfordAQA"></div><div class="f"><label>كود المادة</label><input id="igeCode" required maxlength="40"></div></div><div class="f"><label>اسم المادة</label><input id="igeName" required maxlength="160"></div><div class="split"><div class="f"><label>المستوى</label><select id="igeLevel"><option>OL</option><option>AS</option><option>A2</option><option value="FULL_A_LEVEL">Full A Level</option></select></div><div class="f"><label>نوع القيد</label><select id="igeType"><option value="FIRST_ENTRY">First Entry</option><option value="RETAKE">Retake</option><option value="REMARK">Remark</option><option value="LATE_ENTRY">Late Entry</option></select></div></div><div class="split"><div class="f"><label>Session</label><input id="igeSession" required maxlength="40" placeholder="MAY-JUNE-2027"></div><div class="f"><label>الرسم EGP</label><input id="igeFee" type="number" min="0.01" step="0.01" required></div></div><div class="note">يبدأ DRAFT ولا يؤثر على رصيد أو مدفوعات الطالب.</div><button class="btn primary w">حفظ كمسودة</button></form>');
 document.addEventListener('submit',async e=>{if(e.target.id!=='igExamEntryForm')return;e.preventDefault();const r=await supabase.rpc('create_ig_exam_entry',{p_account:$('#igeAccount').value,p_awarding_body:$('#igeBody').value,p_subject_code:$('#igeCode').value,p_subject_name:$('#igeName').value,p_level:$('#igeLevel').value,p_session_code:$('#igeSession').value,p_entry_type:$('#igeType').value,p_fee_piasters:Math.round(Number($('#igeFee').value)*100)});if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم حفظ رسم المادة كمسودة.','success');await igFinance()});
 window.submitIGExam=async id=>{const r=await supabase.rpc('submit_ig_exam_entry',{p_entry:id});if(r.error)return uiToast(r.error.message,'error',8000);uiToast('تم الإرسال للاعتماد.','success');await igFinance()};
 window.reviewIGExam=async(id,action,reason=null)=>{const r=await supabase.rpc('review_ig_exam_entry',{p_entry:id,p_action:action,p_reason:reason});if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast(action==='APPROVE'?'تم الاعتماد.':'تم الرفض.','success');await igFinance()};
 window.reviewIGExamDialog=id=>openM('رفض رسم مادة IG','<form id="igRejectForm"><input id="igRejectId" type="hidden" value="'+id+'"><div class="f"><label>سبب الرفض *</label><textarea id="igRejectReason" required minlength="3"></textarea></div><button class="btn danger w">تأكيد الرفض</button></form>');
 document.addEventListener('submit',e=>{if(e.target.id!=='igRejectForm')return;e.preventDefault();reviewIGExam($('#igRejectId').value,'REJECT',$('#igRejectReason').value)});
 window.igExamDetail=id=>{const x=rows.find(v=>v.id===id);if(!x)return;openM('تفاصيل رسم مادة IG','<div class="grid cards">'+metric('الرسوم',egp(x.fee_piasters),'')+metric('المدفوع المعتمد',egp(x.paid_piasters),'POSTED فقط','green')+metric('المتبقي',egp(x.remaining_piasters),'','amber')+'</div><div class="card"><p><strong>'+esc(x.subject_name)+'</strong> — '+esc(x.subject_code)+'</p><p>'+esc(x.awarding_body)+' | '+esc(labels[x.level]||x.level)+' | '+esc(x.session_code)+' | '+esc(labels[x.entry_type]||x.entry_type)+'</p><p>'+pill(x.status)+'</p></div>')};
 window.newIGExamReceipt=account=>{const open=rows.filter(x=>x.status==='POSTED'&&Number(x.remaining_piasters)>0&&(!account||x.account_id===account));if(!open.length)return uiToast('لا توجد رسوم مواد معتمدة وغير مسددة.','warning');const selected=account||open[0].account_id,available=open.filter(x=>x.account_id===selected);openM('تحصيل متعدد مواد IG','<form id="igExamPayForm"><input id="igPayAccount" type="hidden" value="'+selected+'"><div class="note">يمكن دفع جزء من كل مادة وتجميع عدة مواد في إيصال واحد.</div>'+available.map(x=>'<div class="cashier-line"><label><input class="igPayCheck" type="checkbox" value="'+x.id+'"> '+esc(x.subject_code+' — '+x.subject_name+' — '+x.session_code)+'</label><span>'+egp(x.remaining_piasters)+'</span><input class="igPayAmount" data-id="'+x.id+'" type="number" min="0" max="'+(Number(x.remaining_piasters)/100)+'" step="0.01" value="0"><span></span></div>').join('')+'<div class="split"><div class="f"><label>التاريخ</label><input id="igPayDate" type="date" value="'+new Date().toISOString().slice(0,10)+'" required></div><div class="f"><label>طريقة الدفع</label><select id="igPayMethod"><option>CASH</option><option>QNB</option><option>ALEX_BANK</option><option>VISA_POS</option><option>OTHER</option></select></div></div><div class="f"><label>المرجع</label><input id="igPayReference"></div><button class="btn primary w">حفظ الإيصال كمسودة</button></form>')};
 document.addEventListener('submit',async e=>{if(e.target.id!=='igExamPayForm')return;e.preventDefault();const lines=[...document.querySelectorAll('.igPayCheck:checked')].map(c=>{const x=rows.find(r=>r.id===c.value),amount=document.querySelector('.igPayAmount[data-id="'+c.value+'"]').value;return {ig_exam_entry_id:c.value,description:x.subject_code+' — '+x.subject_name+' — '+x.session_code,paid_now_piasters:Math.round(Number(amount)*100)}}).filter(x=>x.paid_now_piasters>0);const total=lines.reduce((s,x)=>s+x.paid_now_piasters,0);if(!total)return uiToast('اختر مادة وأدخل مبلغًا صحيحًا.','warning');const r=await supabase.rpc('create_ig_exam_payment_batch',{p_account_id:$('#igPayAccount').value,p_transaction_date:$('#igPayDate').value,p_idempotency_key:crypto.randomUUID(),p_lines:lines,p_tenders:[{method:$('#igPayMethod').value,amount_piasters:total,reference:$('#igPayReference').value}],p_notes:'IG exam fees'});if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم حفظ إيصال IG كمسودة؛ لا يؤثر ماليًا قبل اعتماد د. أماني.','success');await igFinance()});
 const previous=igFinance;igFinance=async function(){await previous();try{await appendIGExamFees()}catch(e){$('#content').insertAdjacentHTML('beforeend','<div class="msg err">تعذر تحميل رسوم مواد IG: '+esc(e.message||e)+'</div>')}};
})();
