(()=>{
 const roles=['OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT','TREASURY','AUDITOR'];Object.assign(pages,{inventory:'المخازن العامة'});roles.forEach(r=>{access[r]||(access[r]=[]);if(!access[r].includes('inventory'))access[r].push('inventory')});const oldRenderInventory=render;
 const all=async(t,s='*',order='created_at')=>{let out=[],from=0;while(true){let q=supabase.from(t).select(s).range(from,from+999);if(order)q=q.order(order,{ascending:false});const r=await q;if(r.error)throw r.error;out.push(...(r.data||[]));if((r.data||[]).length<1000)break;from+=1000}return out};
 const tabs=a=>'<div class="module-tabs">'+[['balances','الأرصدة'],['items','الأصناف'],['movements','الحركات'],['warehouses','المخازن'],['counts','الجرد']].map(x=>'<button class="btn '+(a===x[0]?'on':'ghost')+'" onclick="showInventory(\''+x[0]+'\')">'+x[1]+'</button>').join('')+'</div>';
 async function inventoryPage(){if(!roles.includes(profile.role))return $('#content').innerHTML='<div class="msg err">غير مصرح.</div>';const [w,i,b,m,c]=await Promise.all([all('inventory_warehouses'),all('inventory_items','*,inventory_categories(category_name)'),all('inventory_balances','*,inventory_warehouses(warehouse_code,warehouse_name),inventory_items(sku,item_name,minimum_quantity)','updated_at'),all('inventory_movements'),all('inventory_counts')]);window._inventory={warehouses:w,items:i,balances:b,movements:m,counts:c};const qty=b.reduce((s,x)=>s+Number(x.quantity||0),0),value=b.reduce((s,x)=>s+Number(x.quantity||0)*Number(x.average_cost_piasters||0),0),low=b.filter(x=>Number(x.quantity)<=Number(x.inventory_items?.minimum_quantity||0)).length;$('#content').innerHTML='<div class="grid cards">'+metric('الأصناف',n(i.length),'SKU')+metric('إجمالي الكمية',n(qty),'كل المخازن')+metric('قيمة المخزون',egp(value),'متوسط التكلفة')+metric('تنبيهات إعادة الطلب',n(low),'','amber')+'</div><div class="sec"><h3>المخازن العامة</h3><input id="inventorySearch" placeholder="بحث في الجدول الحالي" oninput="showInventory(window._inventoryTab||\'balances\')"></div>'+tabs('balances')+'<div id="inventoryHost"></div><div class="note">الحركات DRAFT وSUBMITTED لا تغيّر الرصيد. POSTED فقط يدخل Stock Card والأرصدة، والمخزون السالب ممنوع من الخادم.</div>';showInventory('balances')}
 const cfg={balances:{h:['المخزن','SKU','الصنف','الكمية','متوسط التكلفة','القيمة'],k:['inventory_warehouses.warehouse_name','inventory_items.sku','inventory_items.item_name','quantity','average_cost_piasters','value']},items:{h:['SKU','Barcode','الصنف','الفئة','الوحدة','الحد الأدنى','إعادة الطلب'],k:['sku','barcode','item_name','inventory_categories.category_name','unit','minimum_quantity','reorder_quantity']},movements:{h:['الرقم','التاريخ','النوع','الحالة','المصدر'],k:['movement_number','movement_date','movement_type','status','source_table']},warehouses:{h:['الكود','المخزن','الموقع','نشط'],k:['warehouse_code','warehouse_name','location','active']},counts:{h:['رقم الجرد','المخزن','التاريخ','الحالة'],k:['count_number','warehouse_id','count_date','status']}};
 const get=(x,k)=>k==='value'?Number(x.quantity||0)*Number(x.average_cost_piasters||0):k.split('.').reduce((o,p)=>o?.[p],x),money=k=>['average_cost_piasters','value'].includes(k);
 window.showInventory=t=>{window._inventoryTab=t;const c=cfg[t],q=($('#inventorySearch')?.value||'').toLocaleLowerCase('ar'),a=(window._inventory?.[t]||[]).filter(x=>!q||JSON.stringify(x).toLocaleLowerCase('ar').includes(q));$('#inventoryHost').innerHTML='<div class="tools"><button class="btn ghost" onclick="printTable()">طباعة / PDF</button><button class="btn ghost" onclick="downloadTableCSV()">CSV / Excel</button></div><div class="tablewrap"><table id="inventoryTable" class="tbl"><thead><tr>'+c.h.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+(a.map(x=>'<tr onclick="openInventoryRecord(\''+t+'\',\''+(x.id||x.item_id)+'\')">'+c.k.map(k=>'<td>'+esc(money(k)?egp(get(x,k)):String(get(x,k)??'—'))+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="'+c.h.length+'">لا توجد بيانات.</td></tr>')+'</tbody></table></div>'};
 window.openInventoryRecord=async(t,id)=>{const x=(window._inventory?.[t]||[]).find(v=>(v.id||v.item_id)===id);if(!x)return;let card='';if(t==='items'){const r=await supabase.from('v_inventory_stock_card').select('*').eq('item_id',x.id).order('movement_date',{ascending:false});card='<h3>Stock Card</h3><div class="tablewrap"><table class="tbl"><thead><tr><th>التاريخ</th><th>الحركة</th><th>النوع</th><th>الكمية</th><th>الحالة</th></tr></thead><tbody>'+((r.data||[]).map(v=>'<tr><td>'+esc(v.movement_date)+'</td><td>'+esc(v.movement_number)+'</td><td>'+esc(v.movement_type)+'</td><td>'+esc(v.quantity)+'</td><td>'+pill(v.status)+'</td></tr>').join('')||'<tr><td colspan="5">لا توجد حركات.</td></tr>')+'</tbody></table></div>'}let act='';if(t==='movements'&&x.status==='DRAFT'&&['OWNER','FINANCE_MANAGER','ACCOUNTANT','TREASURY'].includes(profile.role))act='<button class="btn primary" onclick="inventoryAction(\'submit_inventory_movement\',\''+x.id+'\')">إرسال</button>';if(t==='movements'&&x.status==='SUBMITTED'&&['OWNER','FINANCE_MANAGER'].includes(profile.role))act='<button class="btn ok" onclick="inventoryAction(\'post_inventory_movement\',\''+x.id+'\')">اعتماد وترحيل</button>';openM('تفاصيل المخزون','<pre style="white-space:pre-wrap;direction:rtl">'+esc(JSON.stringify(x,null,2))+'</pre>'+card+'<div class="tools">'+act+'</div>')};
 window.inventoryAction=async(fn,id)=>{const r=await supabase.rpc(fn,{p_movement:id});if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم تنفيذ الإجراء وتسجيله.','success');await inventoryPage()};
 render=async function(){if(page==='inventory')return inventoryPage();return oldRenderInventory()};
})();
