(()=>{
 Object.assign(access,{
  CASHIER:['dashboard','students','cashier','security','support'],
  TREASURY_MANAGER:['dashboard','approvals','treasury','cheques','banks','reports','security','support'],
  STOREKEEPER:['dashboard','inventory','reports','security','support'],
  PROCUREMENT:['dashboard','procurement','inventory','reports','security','support'],
  APPROVER:['dashboard','approvals','reports','security','support']
 });
 const GROUPS=[
  ['الرئيسية',[['dashboard','Dashboard'],['approvals','الموافقات المعلقة'],['system_check','فحص النظام']]],
  ['الطلاب والتحصيل',[['students','الطلاب وملفاتهم'],['cashier','التحصيل الموحد والإيصالات'],['buses','الباص والنقل'],['uniform','الكتب والزي المدرسي'],['ig','رسوم IG والمواد'],['admissions','التقديم والقبول']]],
  ['المالية والخزنة',[['treasury','الخزنة اليومية والمقبوضات'],['expenses','المصروفات'],['cheques','الشيكات الواردة والصادرة'],['banks','البنوك والمطابقة'],['ledger','القيود والتسويات'],['periods','الفترات والإغلاق']]],
  ['الموارد البشرية',[['hr','الموظفون وعمليات HR']]],
  ['المشتريات والمخازن',[['procurement','المشتريات والموردون'],['inventory','الأصناف والمخازن والجرد']]],
  ['الأصول الثابتة',[['assets','سجل الأصول ودورة الحياة']]],
  ['التقارير',[['reports','مركز التقارير'],['audit','Audit Trail']]],
  ['الإعدادات والإدارة',[['users','المستخدمون والصلاحيات'],['organization','المدارس والفروع'],['security','الأمان وMFA'],['backup','النسخ الاحتياطي'],['support','الدعم والقانونية']]]
 ];
 const allowed=key=>(access[profile?.role]||[]).includes(key);
 const favKey=()=>`bf-favorites:${session?.user?.id||'anon'}`;
 const favorites=()=>{try{return JSON.parse(localStorage.getItem(favKey())||'[]')}catch{return []}};
 const saveFavorites=x=>localStorage.setItem(favKey(),JSON.stringify(x));
 const oldBuildNav=buildNav;
 buildNav=function(){
  if(!profile)return oldBuildNav();
  const fav=favorites(),groups=GROUPS.map(([name,items])=>[name,items.filter(x=>allowed(x[0]))]).filter(x=>x[1].length);
  $('#nav').innerHTML='<div class="nav-search"><input id="screenSearch" aria-label="بحث عن شاشة" placeholder="بحث عن شاشة…"></div>'+groups.map(([name,items],i)=>'<section class="nav-group"><button class="nav-group-title" type="button" aria-expanded="'+(i<2?'true':'false')+'"><span>'+esc(name)+'</span><b>⌄</b></button><div class="nav-group-items '+(i<2?'':'hidden')+'">'+items.map(([k,label])=>'<div class="nav-entry"><button data-p="'+k+'" class="'+(k===page?'on':'')+'">'+esc(label)+'</button><button class="nav-fav" data-fav="'+k+'" title="مفضلة" aria-label="إضافة للمفضلة">'+(fav.includes(k)?'★':'☆')+'</button></div>').join('')+'</div></section>').join('');
  $('#nav').onclick=async e=>{const group=e.target.closest('.nav-group-title');if(group){const box=group.nextElementSibling,open=box.classList.toggle('hidden');group.setAttribute('aria-expanded',String(!open));return}const star=e.target.closest('[data-fav]');if(star){const k=star.dataset.fav,a=favorites(),i=a.indexOf(k);i<0?a.push(k):a.splice(i,1);saveFavorites(a);star.textContent=i<0?'★':'☆';return}const b=e.target.closest('button[data-p]');if(!b)return;page=b.dataset.p;buildNav();await render()};
  $('#screenSearch').oninput=e=>{const q=e.target.value.trim().toLocaleLowerCase('ar');$$('.nav-entry').forEach(x=>x.classList.toggle('hidden',q&&!x.textContent.toLocaleLowerCase('ar').includes(q)));$$('.nav-group-items').forEach(x=>{if(q)x.classList.remove('hidden')})};
 };

 const canWrite=()=>!['READ_ONLY','AUDITOR','DR_AMANY_APPROVER'].includes(profile?.role);
 const addTopChrome=()=>{
  const title=pages[page]||'Bradford ERP',crumb=$('#breadcrumb');if(crumb)crumb.textContent='Bradford ERP / '+title;
  const quick=$('#quickCreate');if(quick){quick.classList.toggle('hidden',!canWrite());quick.onclick=()=>quickCreate()}
 };
 const oldRender=render;
 render=async function(){const out=await oldRender();addTopChrome();installPageActions();return out};

 const topTools=()=>$('#content .sec .tools')||$('#content .sec')||$('#content');
 function addAction(id,label,fn){if(!canWrite()||$('#'+id))return;const b=document.createElement('button');b.id=id;b.className='btn primary';b.textContent='+ '+label;b.onclick=fn;topTools()?.prepend(b)}
 function installPageActions(){
  if(page==='procurement'){const t=window._procTab||'requisitions';if(t==='requisitions')addAction('addPR','طلب شراء',newPurchaseRequisition);if(t==='vendors')addAction('addVendor','مورد',newVendor);if(t==='rfqs'){addAction('addRFQ','RFQ',newRFQ);addAction('addQuote','عرض سعر',newQuotation);addAction('addComparison','مقارنة عروض',newQuoteComparison)}if(t==='orders')addAction('addPO','أمر شراء',newPurchaseOrder);if(t==='receipts')addAction('addGRN','استلام مشتريات',newGoodsReceipt);if(t==='bills')addAction('addBill','فاتورة مورد',newVendorBill);if(t==='returns')addAction('addReturn','مرتجع مشتريات',newPurchaseReturn)}
  if(page==='inventory'){const t=window._inventoryTab||'balances';if(t==='items')addAction('addItem','صنف',newInventoryItem);if(t==='movements')addAction('addMovement','حركة مخزن',newInventoryMovement);if(t==='counts')addAction('addCount','جرد مخزن',newInventoryCount)}
  if(page==='assets'){addAction('addAsset','أصل ثابت',newFixedAsset);addAction('addMaintenance','صيانة أصل',newAssetMaintenance);addAction('addTransfer','نقل أصل',newAssetTransfer);addAction('addDisposal','استبعاد / بيع أصل',newAssetDisposal)}
  if(page==='cheques')addAction('addCheque','شيك',newCheque);
  if(page==='buses'){const t=window._transportOpsTab||'enrollments';if(t==='enrollments')addAction('addBusEnrollment','اشتراك باص',newBusEnrollment);if(t==='trips')addAction('addTrip','رحلة',newTransportTrip);if(t==='vehicles')addAction('addVehicle','مركبة',newTransportVehicle);if(t==='staff')addAction('addTransportStaff','سائق / مشرف',newTransportStaff)}
  if(page==='hr')installHRActions();
 }
 const oldShowProcurement=window.showProcurement;window.showProcurement=t=>{oldShowProcurement(t);setTimeout(installPageActions,0)};
 const oldShowInventory=window.showInventory;window.showInventory=t=>{oldShowInventory(t);setTimeout(installPageActions,0)};
 const oldShowTransportOps=window.showTransportOps;window.showTransportOps=t=>{oldShowTransportOps(t);setTimeout(installPageActions,0)};
 const oldOpenHRModule=window.openHRModule;window.openHRModule=async m=>{await oldOpenHRModule(m);installPageActions()};

 function busy(form,on=true){const b=form.querySelector('[type=submit]');if(b){b.disabled=on;b.dataset.label||=b.textContent;b.textContent=on?'جاري الحفظ…':b.dataset.label}}
 async function finish(r,form,message,refresh=true){busy(form,false);if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast(message,'success');if(refresh)await render()}
 const form=(id,body,label='حفظ كمسودة')=>'<form id="'+id+'">'+body+'<button class="btn primary w" type="submit">'+label+'</button></form>';
 const f=(id,label,type='text',extra='')=>'<div class="f"><label for="'+id+'">'+label+'</label><input id="'+id+'" type="'+type+'" '+extra+'></div>';
 const select=(id,label,opts)=>'<div class="f"><label for="'+id+'">'+label+'</label><select id="'+id+'">'+opts+'</select></div>';

 window.quickCreate=()=>{const actions=[['طالب','newStudent'],['إيصال موحد','cashierOpenWizard'],['مصروف','newExpense'],['موظف','newHREmployee'],['طلب شراء','newPurchaseRequisition'],['صنف','newInventoryItem'],['حركة مخزن','newInventoryMovement'],['شيك','newCheque'],['أصل ثابت','newFixedAsset']].filter(x=>typeof window[x[1]]==='function');openM('إجراء سريع جديد','<div class="quick-create-grid">'+actions.map(x=>'<button class="card btn ghost" onclick="closeM();'+x[1]+'()">+ '+esc(x[0])+'</button>').join('')+'</div>')};

 window.newPurchaseRequisition=()=>openM('إضافة طلب شراء',form('prCreate','<div class="split">'+f('prDepartment','القسم')+f('prEstimate','القيمة التقديرية EGP','number','min="0" step="0.01" required')+'</div><div class="f"><label>الغرض والمواصفات *</label><textarea id="prPurpose" minlength="3" required></textarea></div><div class="note">يبدأ DRAFT ولا ينشئ قيدًا أو حركة مخزون.</div>'));
 window.newVendor=()=>openM('إضافة مورد',form('vendorCreate','<div class="split">'+f('vendorCode','كود المورد *','text','required maxlength="40"')+f('vendorName','الاسم القانوني *','text','required maxlength="180"')+'</div><div class="split">'+f('vendorTax','الرقم الضريبي')+f('vendorCR','السجل التجاري')+'</div><div class="split">'+f('vendorPhone','الهاتف','tel')+f('vendorEmail','البريد','email')+'</div>'+f('vendorAddress','العنوان')));
 window.editVendor=id=>{const v=(window._proc?.vendors||[]).find(x=>x.id===id);if(!v)return uiToast('تعذر العثور على المورد.','error');openM('تعديل المورد',form('vendorEdit','<input id="vendorEditId" type="hidden" value="'+esc(v.id)+'"><div class="split">'+f('vendorCode','كود المورد *','text','required maxlength="40" value="'+esc(v.vendor_code||'')+'"')+f('vendorName','الاسم القانوني *','text','required maxlength="180" value="'+esc(v.legal_name||v.name||'')+'"')+'</div><div class="split">'+f('vendorTax','الرقم الضريبي','text','value="'+esc(v.tax_id||'')+'"')+f('vendorCR','السجل التجاري','text','value="'+esc(v.commercial_register||'')+'"')+'</div><div class="split">'+f('vendorPhone','الهاتف','tel','value="'+esc(v.phone||'')+'"')+f('vendorEmail','البريد','email','value="'+esc(v.email||'')+'"')+'</div>'+f('vendorAddress','العنوان','text','value="'+esc(v.address||'')+'"'),'حفظ التعديل'))};
 window.newQuotation=()=>{const vendors=window._proc?.vendors||[],prs=window._proc?.requisitions||[];openM('إضافة عرض سعر',form('quoteCreate',select('quoteVendor','المورد *',vendors.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join(''))+select('quotePR','طلب الشراء','<option value="">—</option>'+prs.map(x=>'<option value="'+x.id+'">'+esc(x.pr_number)+'</option>').join(''))+'<div class="split">'+f('quoteNo','رقم العرض')+f('quoteDate','تاريخ العرض','date','required')+'</div><div class="split">'+f('quoteAmount','الإجمالي EGP','number','min="0.01" step="0.01" required')+f('quoteValid','صالح حتى','date')+'</div>'+f('quoteDelivery','مدة التوريد بالأيام','number','min="0"')))};
 window.newInventoryItem=()=>{const cats=window._inventory?.items?.map(x=>x.inventory_categories).filter(Boolean)||[];openM('إضافة صنف',form('itemCreate','<div class="split">'+f('itemSku','SKU *','text','required maxlength="80"')+f('itemBarcode','Barcode / QR')+'</div>'+f('itemName','اسم الصنف *','text','required maxlength="180"')+'<div class="split">'+f('itemUnit','الوحدة *','text','required value="EA"')+f('itemSize','المقاس')+'</div><div class="split">'+f('itemMin','الحد الأدنى','number','min="0" step="0.01" value="0"')+f('itemReorder','كمية إعادة الطلب','number','min="0" step="0.01" value="0"')+'</div>'))};
 window.newInventoryMovement=()=>{const d=window._inventory||{},ware=d.warehouses||[],items=d.items||[],wo='<option value="">—</option>'+ware.map(x=>'<option value="'+x.id+'">'+esc(x.warehouse_code+' — '+x.warehouse_name)+'</option>').join('');openM('إضافة حركة مخزن',form('movementCreate',select('moveType','نوع الحركة','<option>RECEIPT</option><option>ISSUE</option><option>RETURN_IN</option><option>RETURN_OUT</option><option>TRANSFER</option><option>ADJUSTMENT_IN</option><option>ADJUSTMENT_OUT</option><option>DAMAGE</option><option>WASTE</option><option>COUNT</option>')+'<div class="split">'+select('moveFrom','المخزن المصدر',wo)+select('moveTo','المخزن الوجهة',wo)+'</div>'+select('moveItem','الصنف *',items.map(x=>'<option value="'+x.id+'">'+esc(x.sku+' — '+x.item_name)+'</option>').join(''))+'<div class="split">'+f('moveQty','الكمية *','number','min="0.001" step="0.001" required')+f('moveCost','سعر الوحدة EGP','number','min="0" step="0.01" value="0"')+'</div>'+f('moveReason','السبب / المرجع')))};
 window.newFixedAsset=()=>openM('إضافة أصل ثابت',form('assetCreate','<div class="split">'+f('assetCode','كود الأصل *','text','required')+f('assetName','اسم الأصل *','text','required')+'</div><div class="split">'+f('assetCategory','التصنيف')+f('assetSerial','الرقم التسلسلي')+'</div><div class="split">'+f('assetDate','تاريخ الشراء','date','required')+f('assetCost','قيمة الشراء EGP','number','min="0.01" step="0.01" required')+'</div><div class="split">'+f('assetLife','العمر الإنتاجي بالأشهر','number','min="1" required')+f('assetRate','الإهلاك السنوي %','number','min="0" max="100" step="0.01" value="20" required')+'</div><div class="split">'+f('assetLocation','الموقع')+f('assetCustodian','المسؤول')+'</div>'));
 window.newCheque=async()=>{const r=await supabase.from('bank_accounts').select('id,bank_name,account_label').order('bank_name');if(r.error)return uiToast(r.error.message,'error');openM('إضافة شيك',form('chequeCreate','<div class="split">'+select('chequeDirection','النوع','<option value="RECEIVABLE">وارد</option><option value="PAYABLE">صادر</option>')+f('chequeNumber','رقم الشيك *','text','required')+'</div>'+select('chequeBank','الحساب البنكي *',(r.data||[]).map(x=>'<option value="'+x.id+'">'+esc(x.bank_name+' — '+x.account_label)+'</option>').join(''))+'<div class="split">'+f('chequeParty','صاحب الشيك / المستفيد *','text','required')+f('chequeAmount','المبلغ EGP *','number','min="0.01" step="0.01" required')+'</div><div class="split">'+f('chequeIssue','تاريخ الإصدار','date','required')+f('chequeDue','تاريخ الاستحقاق','date','required')+'</div>'+f('chequeNotes','ملاحظات')))};
 window.newBusEnrollment=async()=>{const [s,r,v]=await Promise.all([supabase.from('students').select('id,student_code,student_name,grade').eq('status','ACTIVE').order('student_name'),supabase.from('transport_routes').select('id,route_code,route_name,annual_fee_piasters').eq('status','ACTIVE').order('route_name'),supabase.from('transport_vehicles').select('id,vehicle_code,capacity').eq('status','ACTIVE').order('vehicle_code')]);if(s.error||r.error||v.error)return uiToast((s.error||r.error||v.error).message,'error');openM('إضافة اشتراك باص',form('busEnrollmentCreate',select('busStudent','الطالب *',(s.data||[]).map(x=>'<option value="'+x.id+'">'+esc(x.student_code+' — '+x.student_name+' — '+(x.grade||''))+'</option>').join(''))+'<div class="split">'+select('busRoute','المسار *',(r.data||[]).map(x=>'<option value="'+x.id+'" data-fee="'+x.annual_fee_piasters+'">'+esc(x.route_code+' — '+x.route_name)+'</option>').join(''))+select('busVehicle','المركبة','<option value="">—</option>'+(v.data||[]).map(x=>'<option value="'+x.id+'">'+esc(x.vehicle_code+' — '+x.capacity+' مقعد')+'</option>').join(''))+'</div><div class="split">'+f('busPickup','نقطة الركوب *','text','required')+f('busGuardian','هاتف ولي الأمر','tel')+'</div><div class="split">'+f('busYear','السنة الدراسية *','text','required value="2026-2027"')+f('busFee','الرسوم EGP *','number','min="0" step="0.01" required')+'</div>'))};

 const opt=(a,id,label)=>'<option value="">—</option>'+(a||[]).map(x=>'<option value="'+x[id]+'">'+esc(label(x))+'</option>').join('');
 const attachBox=()=>'<div class="f"><label>مرفقات PDF / JPG / PNG</label><input class="operation-files" type="file" accept="application/pdf,image/jpeg,image/png" capture="environment" multiple><div class="attachment-preview note">لم يتم اختيار ملفات.</div></div>';
 document.addEventListener('change',e=>{if(!e.target.matches('.operation-files'))return;const box=e.target.nextElementSibling,files=[...e.target.files];box.innerHTML=files.length?files.map(v=>'<span>'+esc(v.name)+' — '+Math.ceil(v.size/1024)+' KB</span>').join('<br>'):'لم يتم اختيار ملفات.'});
 async function saveAttachments(input,sourceTable,sourceId,documentType='SUPPORTING'){
  const files=[...(input?.files||[])];for(const file of files){if(file.size>10*1024*1024)throw new Error('الملف أكبر من 10MB: '+file.name);if(!['application/pdf','image/jpeg','image/png'].includes(file.type))throw new Error('نوع ملف غير مسموح: '+file.name);const hash=await fileHash(file),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=session.user.id+'/'+sourceTable+'/'+sourceId+'/'+crypto.randomUUID()+'-'+safe;const up=await supabase.storage.from('erp-private-documents').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const ins=await supabase.from('operation_attachments').insert({source_table:sourceTable,source_id:sourceId,document_type:documentType,bucket_id:'erp-private-documents',object_path:path,original_filename:file.name,mime_type:file.type,size_bytes:file.size,sha256:hash,uploaded_by:session.user.id});if(ins.error)throw ins.error}
 }
 window.openOperationAttachment=async id=>{const q=await supabase.from('operation_attachments').select('bucket_id,object_path').eq('id',id).single();if(q.error)return uiToast(q.error.message,'error');const s=await supabase.storage.from(q.data.bucket_id).createSignedUrl(q.data.object_path,120);if(s.error)return uiToast(s.error.message,'error');window.open(s.data.signedUrl,'_blank','noopener')};

 window.newRFQ=()=>{const d=window._proc||{};openM('طلب عروض أسعار RFQ',form('rfqCreate',select('rfqPR','طلب الشراء *',opt(d.requisitions,'id',x=>x.pr_number+' — '+x.purpose))+f('rfqDue','موعد الرد *','datetime-local','required')+f('rfqCount','عدد العروض المطلوبة','number','min="1" value="3" required')+attachBox()))};
 window.newQuoteComparison=async()=>{const r=await supabase.from('vendor_quotations').select('id,quotation_number,amount_piasters,vendors(name),rfq_id').eq('status','DRAFT').order('amount_piasters');if(r.error)return uiToast(r.error.message,'error');openM('مقارنة عروض الأسعار',form('comparisonCreate',select('compareQuote','العرض المختار *',opt(r.data,'id',x=>(x.vendors?.name||'مورد')+' — '+egp(x.amount_piasters)))+f('compareReason','سبب الاختيار *','text','required minlength="3"')+select('compareThree','استيفاء 3 عروض','<option value="true">نعم</option><option value="false">لا — يلزم سبب استثناء</option>')+f('compareException','سبب الاستثناء')))};
 window.newPurchaseOrder=()=>{const d=window._proc||{};openM('أمر شراء جديد',form('poCreate',select('poPR','طلب الشراء *',opt(d.requisitions,'id',x=>x.pr_number))+select('poVendor','المورد *',opt(d.vendors,'id',x=>x.name))+'<div class="split">'+f('poDate','تاريخ الأمر *','date','required')+f('poExpected','التوريد المتوقع','date')+'</div>'+f('poItem','الصنف / المواصفات *','text','required')+'<div class="split">'+f('poQty','الكمية *','number','min="0.001" step="0.001" required')+f('poUnit','الوحدة *','text','required value="EA"')+'</div><div class="split">'+f('poUnitCost','سعر الوحدة EGP *','number','min="0" step="0.01" required')+f('poTax','الضريبة EGP','number','min="0" step="0.01" value="0"')+'</div>'+f('poTerms','شروط الدفع')+attachBox()))};
 window.newGoodsReceipt=async()=>{const d=window._proc||{},l=await supabase.from('purchase_order_lines').select('id,purchase_order_id,item_description,quantity');if(l.error)return uiToast(l.error.message,'error');openM('استلام مشتريات',form('grnCreate',select('grnPO','أمر الشراء *',opt(d.orders,'id',x=>x.po_number))+select('grnPOLine','بند أمر الشراء *',opt(l.data,'id',x=>x.item_description+' — '+x.quantity))+'<div class="split">'+f('grnDate','تاريخ الاستلام *','date','required')+f('grnQty','الكمية المستلمة *','number','min="0.001" step="0.001" required')+'</div>'+f('grnNotes','نتيجة فحص الكمية والجودة')+attachBox()))};
 window.newVendorBill=()=>{const d=window._proc||{};openM('فاتورة مورد',form('billCreate',select('billVendor','المورد *',opt(d.vendors,'id',x=>x.name))+select('billPO','أمر الشراء *',opt(d.orders,'id',x=>x.po_number))+select('billGRN','إذن الاستلام *',opt(d.receipts,'id',x=>x.grn_number))+'<div class="split">'+f('billInvoice','رقم فاتورة المورد *','text','required')+f('billDate','تاريخ الفاتورة *','date','required')+'</div>'+f('billGL','حساب المصروف GL *','text','required placeholder="مثال: 5100"')+'<div class="split">'+f('billNet','الصافي EGP','number','min="0" step="0.01" required')+f('billTax','الضريبة EGP','number','min="0" step="0.01" value="0"')+'</div>'+f('billDesc','البيان *','text','required')+attachBox()))};
 window.newPurchaseReturn=async()=>{const d=window._proc||{},l=await supabase.from('goods_receipt_lines').select('id,goods_receipt_id,quantity_received');if(l.error)return uiToast(l.error.message,'error');openM('مرتجع مشتريات',form('returnCreate',select('returnGRN','إذن الاستلام *',opt(d.receipts,'id',x=>x.grn_number))+select('returnGRNLine','بند الاستلام *',opt(l.data,'id',x=>'كمية مستلمة: '+x.quantity_received))+select('returnVendor','المورد *',opt(d.vendors,'id',x=>x.name))+'<div class="split">'+f('returnDate','تاريخ المرتجع *','date','required')+f('returnQty','الكمية *','number','min="0.001" step="0.001" required')+'</div>'+f('returnUnitCost','تكلفة الوحدة EGP *','number','min="0" step="0.01" required')+f('returnReason','سبب المرتجع *','text','required')+attachBox()))};
 window.newInventoryCount=()=>{const d=window._inventory||{};openM('جرد مخزن',form('countCreate',select('countWarehouse','المخزن *',opt(d.warehouses,'id',x=>x.warehouse_code+' — '+x.warehouse_name))+select('countItem','الصنف *',opt(d.items,'id',x=>x.sku+' — '+x.item_name))+'<div class="split">'+f('countDate','تاريخ الجرد *','date','required')+f('countPhysical','الكمية الفعلية *','number','min="0" step="0.001" required')+'</div>'+f('countNotes','ملاحظات')+attachBox()))};
 window.newTransportVehicle=()=>{const d=window._transportOps||{};openM('إضافة مركبة',form('vehicleCreate','<div class="split">'+f('vehicleCode','كود المركبة *','text','required')+f('vehiclePlate','رقم اللوحة *','text','required')+'</div><div class="split">'+f('vehicleModel','الموديل')+f('vehicleCapacity','السعة *','number','min="1" required')+'</div>'+select('vehicleRoute','المسار',opt(d.routes,'id',x=>x.route_code+' — '+x.route_name))+attachBox()))};
 window.newTransportStaff=()=>{const d=window._transportOps||{};openM('إضافة سائق / مشرف',form('transportStaffCreate','<div class="split">'+f('transportStaffName','الاسم *','text','required')+select('transportStaffRole','الدور','<option value="DRIVER">سائق</option><option value="SUPERVISOR">مشرف</option>')+'</div><div class="split">'+f('transportStaffPhone','الهاتف','tel')+f('transportStaffNational','الرقم القومي')+'</div>'+select('transportStaffVehicle','المركبة',opt(d.vehicles,'id',x=>x.vehicle_code))+attachBox()))};
 window.newTransportTrip=()=>{const d=window._transportOps||{};openM('إضافة رحلة',form('tripCreate',select('tripRoute','المسار *',opt(d.routes,'id',x=>x.route_name))+select('tripVehicle','المركبة *',opt(d.vehicles,'id',x=>x.vehicle_code))+'<div class="split">'+select('tripDriver','السائق',opt((d.staff||[]).filter(x=>x.staff_role==='DRIVER'),'id',x=>x.full_name))+select('tripSupervisor','المشرف',opt((d.staff||[]).filter(x=>x.staff_role==='SUPERVISOR'),'id',x=>x.full_name))+'</div><div class="split">'+f('tripDate','التاريخ *','date','required')+select('tripDirection','الاتجاه','<option>OUTBOUND</option><option>RETURN</option>')+'</div>'+f('tripScheduled','الموعد *','datetime-local','required')+attachBox()))};
 const assetOptions=async()=>{const r=await supabase.from('fixed_assets').select('id,asset_code,asset_name').order('asset_code');if(r.error)throw r.error;return opt(r.data,'id',x=>x.asset_code+' — '+x.asset_name)};
 window.newAssetMaintenance=async()=>openM('صيانة أصل',form('maintenanceCreate',select('maintenanceAsset','الأصل *',await assetOptions())+'<div class="split">'+f('maintenanceType','نوع الصيانة *','text','required')+f('maintenanceDate','التاريخ المجدول','date')+'</div>'+f('maintenanceCost','التكلفة EGP','number','min="0" step="0.01" value="0"')+f('maintenanceDesc','الوصف *','text','required')+attachBox()));
 window.newAssetTransfer=async()=>openM('نقل أصل',form('transferCreate',select('transferAsset','الأصل *',await assetOptions())+'<div class="split">'+f('transferDate','تاريخ النقل *','date','required')+f('transferFrom','من موقع *','text','required')+'</div>'+f('transferTo','إلى موقع *','text','required')+f('transferNotes','ملاحظات')+attachBox()));
 window.newAssetDisposal=async()=>openM('استبعاد أو بيع أصل',form('disposalCreate',select('disposalAsset','الأصل *',await assetOptions())+'<div class="split">'+f('disposalDate','التاريخ *','date','required')+select('disposalType','النوع','<option value="SALE">بيع</option><option value="SCRAP">استبعاد</option><option value="LOSS">فقد</option>')+'</div><div class="split">'+f('disposalProceeds','المتحصل EGP','number','min="0" step="0.01" value="0"')+f('disposalNBV','القيمة الدفترية EGP','number','min="0" step="0.01" value="0"')+'</div>'+f('disposalNotes','السبب / الملاحظات *','text','required')+attachBox()));

 function installHRActions(){const m=window._hrModule;if(m==='employees')addAction('addEmployeeDoc','مستند موظف',newHREmployeeDocument);const map={attendance:['حضور / غياب','newHRAttendance'],leaves:['إجازة / إذن','newHRLeave'],deductions:['خصم / جزاء','newHRDeduction'],cover:['Cover','newHRCover'],compensation:['بدل / مكافأة','newHRCompensation']};if(map[m])addAction('addHRSub',map[m][0],window[map[m][1]])}
 async function hrEmployeeSelect(){if(!window._hrEmployees){const r=await supabase.from('hr_employees').select('id,employee_code,full_name').eq('status','ACTIVE').order('employee_code');if(r.error)throw r.error;window._hrEmployees=r.data||[]}return opt(window._hrEmployees,'id',x=>x.employee_code+' — '+x.full_name)}
 window.newHREmployeeDocument=async()=>openM('مستند موظف',form('hrDocumentCreate',select('hrDocEmployee','الموظف *',await hrEmployeeSelect())+f('hrDocType','نوع المستند *','text','required')+f('hrDocExpiry','تاريخ الانتهاء','date')+f('hrDocNotes','ملاحظات')+attachBox()));
 window.newHRAttendance=async()=>openM('حضور / غياب / تأخير',form('hrAttendanceCreate',select('hrAttendanceEmployee','الموظف *',await hrEmployeeSelect())+'<div class="split">'+f('hrAttendanceDate','التاريخ *','date','required')+select('hrAttendanceStatus','الحالة','<option>PRESENT</option><option>ABSENT</option><option>LEAVE</option>')+'</div><div class="split">'+f('hrCheckIn','الحضور','time')+f('hrCheckOut','الانصراف','time')+'</div><div class="split">'+f('hrLate','دقائق التأخير','number','min="0" value="0"')+f('hrEarly','دقائق الخروج المبكر','number','min="0" value="0"')+'</div>'+f('hrAttendanceNotes','ملاحظات')+attachBox()));
 window.newHRLeave=async()=>openM('إجازة أو إذن',form('hrLeaveCreate',select('hrLeaveEmployee','الموظف *',await hrEmployeeSelect())+f('hrLeaveType','النوع *','text','required')+'<div class="split">'+f('hrLeaveStart','من *','date','required')+f('hrLeaveEnd','إلى *','date','required')+'</div>'+select('hrLeavePaid','مدفوعة','<option value="true">نعم</option><option value="false">لا</option>')+f('hrLeaveReason','السبب *','text','required')+attachBox()));
 window.newHRDeduction=async()=>openM('خصم أو جزاء',form('hrDeductionCreate',select('hrDeductionEmployee','الموظف *',await hrEmployeeSelect())+select('hrDeductionType','النوع','<option>DEDUCTION</option><option>PENALTY</option>')+'<div class="split">'+f('hrDeductionMonth','الشهر *','date','required')+f('hrDeductionAmount','المبلغ EGP *','number','min="0.01" step="0.01" required')+'</div>'+f('hrDeductionDesc','السبب *','text','required')+attachBox()));
 window.newHRCover=async()=>openM('Cover / إضافي',form('hrCoverCreate',select('hrCoverEmployee','الموظف *',await hrEmployeeSelect())+'<div class="split">'+f('hrCoverDate','التاريخ *','date','required')+f('hrCoverPeriods','عدد الحصص *','number','min="0.5" step="0.5" required')+'</div>'+f('hrCoverRate','قيمة الحصة EGP *','number','min="0" step="0.01" required')+f('hrCoverNotes','ملاحظات')+attachBox()));
 window.newHRCompensation=async()=>openM('بدل / مكافأة / تسوية',form('hrCompensationCreate',select('hrCompEmployee','الموظف *',await hrEmployeeSelect())+select('hrCompType','النوع','<option>ALLOWANCE</option><option>BONUS</option><option>COMMISSION</option><option>ADJUSTMENT</option>')+'<div class="split">'+f('hrCompMonth','الشهر *','date','required')+f('hrCompAmount','المبلغ EGP *','number','step="0.01" required')+'</div>'+f('hrCompDesc','البيان *','text','required')+attachBox()));

 document.addEventListener('submit',async e=>{
  const x=e.target;if(!['prCreate','vendorCreate','vendorEdit','quoteCreate','itemCreate','movementCreate','assetCreate','chequeCreate','busEnrollmentCreate','rfqCreate','comparisonCreate','poCreate','grnCreate','billCreate','returnCreate','countCreate','vehicleCreate','transportStaffCreate','tripCreate','maintenanceCreate','transferCreate','disposalCreate','hrDocumentCreate','hrAttendanceCreate','hrLeaveCreate','hrDeductionCreate','hrCoverCreate','hrCompensationCreate'].includes(x.id))return;e.preventDefault();busy(x,true);let r,sourceTable=null;
  if(x.id==='prCreate')r=await supabase.rpc('create_purchase_requisition_draft',{p_department:$('#prDepartment').value,p_purpose:$('#prPurpose').value,p_estimated_total_piasters:Math.round(Number($('#prEstimate').value)*100),p_idempotency_key:crypto.randomUUID()});
  if(x.id==='vendorCreate')r=await supabase.from('vendors').insert({vendor_code:$('#vendorCode').value.trim(),name:$('#vendorName').value.trim(),legal_name:$('#vendorName').value.trim(),tax_id:$('#vendorTax').value.trim()||null,commercial_register:$('#vendorCR').value.trim()||null,phone:$('#vendorPhone').value.trim()||null,email:$('#vendorEmail').value.trim()||null,address:$('#vendorAddress').value.trim()||null,created_by:session.user.id});
  if(x.id==='vendorEdit')r=await supabase.from('vendors').update({vendor_code:$('#vendorCode').value.trim(),name:$('#vendorName').value.trim(),legal_name:$('#vendorName').value.trim(),tax_id:$('#vendorTax').value.trim()||null,commercial_register:$('#vendorCR').value.trim()||null,phone:$('#vendorPhone').value.trim()||null,email:$('#vendorEmail').value.trim()||null,address:$('#vendorAddress').value.trim()||null}).eq('id',$('#vendorEditId').value);
  if(x.id==='quoteCreate')r=await supabase.from('vendor_quotations').insert({vendor_id:$('#quoteVendor').value,requisition_id:$('#quotePR').value||null,quotation_number:$('#quoteNo').value.trim()||null,quotation_date:$('#quoteDate').value,amount_piasters:Math.round(Number($('#quoteAmount').value)*100),valid_until:$('#quoteValid').value||null,delivery_days:Number($('#quoteDelivery').value)||null,status:'DRAFT',created_by:session.user.id});
  if(x.id==='itemCreate')r=await supabase.from('inventory_items').insert({sku:$('#itemSku').value.trim(),barcode:$('#itemBarcode').value.trim()||null,item_name:$('#itemName').value.trim(),unit:$('#itemUnit').value.trim(),size:$('#itemSize').value.trim()||null,minimum_quantity:Number($('#itemMin').value)||0,reorder_quantity:Number($('#itemReorder').value)||0,created_by:session.user.id,updated_by:session.user.id});
  if(x.id==='movementCreate')r=await supabase.rpc('create_inventory_movement_draft',{p_movement_type:$('#moveType').value,p_from_warehouse:$('#moveFrom').value||null,p_to_warehouse:$('#moveTo').value||null,p_item:$('#moveItem').value,p_quantity:Number($('#moveQty').value),p_unit_cost_piasters:Math.round(Number($('#moveCost').value||0)*100),p_reason:$('#moveReason').value,p_idempotency_key:crypto.randomUUID()});
  if(x.id==='assetCreate')r=await supabase.from('fixed_assets').insert({asset_code:$('#assetCode').value.trim(),asset_name:$('#assetName').value.trim(),category:$('#assetCategory').value.trim()||null,asset_tag:$('#assetSerial').value.trim()||null,purchase_date:$('#assetDate').value,acquisition_cost_piasters:Math.round(Number($('#assetCost').value)*100),useful_life_months:Number($('#assetLife').value),depreciation_rate:Number($('#assetRate').value)/100,location:$('#assetLocation').value.trim()||null,responsibility:'NEEDS_REVIEW',notes:$('#assetCustodian').value.trim()||null,created_by:session.user.id,updated_by:session.user.id});
  if(x.id==='chequeCreate')r=await supabase.from('cheques').insert({cheque_number:$('#chequeNumber').value.trim(),bank_account_id:$('#chequeBank').value,direction:$('#chequeDirection').value==='RECEIVABLE'?'RECEIVED':'ISSUED',beneficiary:$('#chequeParty').value.trim(),amount_piasters:Math.round(Number($('#chequeAmount').value)*100),issue_date:$('#chequeIssue').value,due_date:$('#chequeDue').value,status:'DRAFT',notes:$('#chequeNotes').value.trim()||null,created_by:session.user.id,updated_by:session.user.id});
  if(x.id==='busEnrollmentCreate')r=await supabase.from('transport_enrollments').insert({student_id:$('#busStudent').value,route_id:$('#busRoute').value,vehicle_id:$('#busVehicle').value||null,pickup_point:$('#busPickup').value.trim(),guardian_phone:$('#busGuardian').value.trim()||null,academic_year:$('#busYear').value.trim(),fee_piasters:Math.round(Number($('#busFee').value)*100),status:'ACTIVE',created_by:session.user.id,updated_by:session.user.id});
  if(x.id==='rfqCreate'){sourceTable='procurement_rfqs';r=await supabase.from(sourceTable).insert({requisition_id:$('#rfqPR').value,response_due_at:new Date($('#rfqDue').value).toISOString(),required_quote_count:Number($('#rfqCount').value),status:'DRAFT',created_by:session.user.id,updated_by:session.user.id}).select('id').single()}
  if(x.id==='comparisonCreate'){const q=(window._proc?.rfqs||[]).find(v=>v.id===(window._proc?.quotations||[]).find(z=>z.id===$('#compareQuote').value)?.rfq_id);r=await supabase.from('procurement_quote_decisions').insert({rfq_id:q?.id||null,selected_quotation_id:$('#compareQuote').value,comparison:{source:'OPERATIONAL_UI'},decision_reason:$('#compareReason').value.trim(),three_quotes_met:$('#compareThree').value==='true',exception_reason:$('#compareException').value.trim()||null})}
  if(x.id==='poCreate'){sourceTable='purchase_orders';const qty=Number($('#poQty').value),unitCost=Math.round(Number($('#poUnitCost').value)*100),net=Math.round(qty*unitCost),tax=Math.round(Number($('#poTax').value)*100);r=await supabase.from(sourceTable).insert({requisition_id:$('#poPR').value,vendor_id:$('#poVendor').value,order_date:$('#poDate').value,expected_date:$('#poExpected').value||null,status:'DRAFT',subtotal_piasters:net,tax_piasters:tax,total_piasters:net+tax,payment_terms:$('#poTerms').value.trim()||null,created_by:session.user.id}).select('id').single();if(!r.error){const l=await supabase.from('purchase_order_lines').insert({purchase_order_id:r.data.id,line_no:1,item_description:$('#poItem').value.trim(),quantity:qty,unit:$('#poUnit').value.trim(),unit_cost_piasters:unitCost,line_total_piasters:net});if(l.error)r={error:l.error}}}
  if(x.id==='grnCreate'){sourceTable='goods_receipts';r=await supabase.from(sourceTable).insert({purchase_order_id:$('#grnPO').value,receipt_date:$('#grnDate').value,status:'DRAFT',received_by:session.user.id,notes:$('#grnNotes').value.trim()||null}).select('id').single();if(!r.error){const l=await supabase.from('goods_receipt_lines').insert({goods_receipt_id:r.data.id,purchase_order_line_id:$('#grnPOLine').value,quantity_received:Number($('#grnQty').value),notes:$('#grnNotes').value.trim()||null});if(l.error)r={error:l.error}}}
  if(x.id==='billCreate'){sourceTable='vendor_bills';const net=Math.round(Number($('#billNet').value)*100),tax=Math.round(Number($('#billTax').value)*100);r=await supabase.from(sourceTable).insert({vendor_id:$('#billVendor').value,purchase_order_id:$('#billPO').value,goods_receipt_id:$('#billGRN').value,supplier_invoice_number:$('#billInvoice').value.trim(),invoice_date:$('#billDate').value,description:$('#billDesc').value.trim(),gl_account_code:$('#billGL').value.trim(),net_piasters:net,tax_piasters:tax,total_piasters:net+tax,status:'DRAFT',match_status:'PENDING',created_by:session.user.id}).select('id').single()}
  if(x.id==='returnCreate'){sourceTable='purchase_returns';r=await supabase.from(sourceTable).insert({goods_receipt_id:$('#returnGRN').value,vendor_id:$('#returnVendor').value,return_date:$('#returnDate').value,status:'DRAFT',reason:$('#returnReason').value.trim(),created_by:session.user.id}).select('id').single();if(!r.error){const q=Number($('#returnQty').value),c=Math.round(Number($('#returnUnitCost').value)*100),l=await supabase.from('purchase_return_lines').insert({purchase_return_id:r.data.id,goods_receipt_line_id:$('#returnGRNLine').value,quantity:q,unit_cost_piasters:c,line_total_piasters:Math.round(q*c)});if(l.error)r={error:l.error}}}
  if(x.id==='countCreate'){sourceTable='inventory_counts';r=await supabase.from(sourceTable).insert({warehouse_id:$('#countWarehouse').value,count_date:$('#countDate').value,status:'DRAFT',notes:$('#countNotes').value.trim()||null,created_by:session.user.id}).select('id').single();if(!r.error){const l=await supabase.from('inventory_count_lines').insert({count_id:r.data.id,item_id:$('#countItem').value,system_quantity:0,physical_quantity:Number($('#countPhysical').value)});if(l.error)r={error:l.error}}}
  if(x.id==='vehicleCreate'){sourceTable='transport_vehicles';r=await supabase.from(sourceTable).insert({vehicle_code:$('#vehicleCode').value.trim(),plate_number:$('#vehiclePlate').value.trim(),model:$('#vehicleModel').value.trim()||null,capacity:Number($('#vehicleCapacity').value),route_id:$('#vehicleRoute').value||null,status:'ACTIVE',created_by:session.user.id,updated_by:session.user.id}).select('id').single()}
  if(x.id==='transportStaffCreate'){sourceTable='transport_staff';r=await supabase.from(sourceTable).insert({full_name:$('#transportStaffName').value.trim(),staff_role:$('#transportStaffRole').value,phone:$('#transportStaffPhone').value.trim()||null,national_id:$('#transportStaffNational').value.trim()||null,vehicle_id:$('#transportStaffVehicle').value||null,status:'ACTIVE',created_by:session.user.id,updated_by:session.user.id}).select('id').single()}
  if(x.id==='tripCreate'){sourceTable='transport_trips';r=await supabase.from(sourceTable).insert({route_id:$('#tripRoute').value,vehicle_id:$('#tripVehicle').value,driver_id:$('#tripDriver').value||null,supervisor_id:$('#tripSupervisor').value||null,trip_date:$('#tripDate').value,direction:$('#tripDirection').value,scheduled_at:new Date($('#tripScheduled').value).toISOString(),status:'SCHEDULED',created_by:session.user.id,updated_by:session.user.id}).select('id').single()}
  if(x.id==='maintenanceCreate'){sourceTable='asset_maintenance';r=await supabase.from(sourceTable).insert({asset_id:$('#maintenanceAsset').value,maintenance_type:$('#maintenanceType').value.trim(),scheduled_date:$('#maintenanceDate').value||null,cost_piasters:Math.round(Number($('#maintenanceCost').value)*100),status:'SCHEDULED',description:$('#maintenanceDesc').value.trim(),created_by:session.user.id,updated_by:session.user.id}).select('id').single()}
  if(x.id==='transferCreate'){sourceTable='asset_transfers';r=await supabase.from(sourceTable).insert({asset_id:$('#transferAsset').value,transfer_date:$('#transferDate').value,from_location:$('#transferFrom').value.trim(),to_location:$('#transferTo').value.trim(),notes:$('#transferNotes').value.trim()||null,created_by:session.user.id}).select('id').single()}
  if(x.id==='disposalCreate'){sourceTable='asset_disposals';const p=Math.round(Number($('#disposalProceeds').value)*100),b=Math.round(Number($('#disposalNBV').value)*100);r=await supabase.from(sourceTable).insert({asset_id:$('#disposalAsset').value,disposal_date:$('#disposalDate').value,disposal_type:$('#disposalType').value,proceeds_piasters:p,net_book_value_piasters:b,gain_loss_piasters:p-b,status:'DRAFT',notes:$('#disposalNotes').value.trim(),created_by:session.user.id}).select('id').single()}
  if(x.id==='hrDocumentCreate'){sourceTable='hr_employee_documents';r=await supabase.from(sourceTable).insert({employee_id:$('#hrDocEmployee').value,document_type:$('#hrDocType').value.trim(),expiry_date:$('#hrDocExpiry').value||null,verified:false,notes:$('#hrDocNotes').value.trim()||null,document_url:'PRIVATE_ATTACHMENT',created_by:session.user.id}).select('id').single()}
  if(x.id==='hrAttendanceCreate'){sourceTable='hr_attendance';r=await supabase.from(sourceTable).insert({employee_id:$('#hrAttendanceEmployee').value,work_date:$('#hrAttendanceDate').value,check_in:$('#hrCheckIn').value||null,check_out:$('#hrCheckOut').value||null,late_minutes:Number($('#hrLate').value)||0,early_leave_minutes:Number($('#hrEarly').value)||0,status:$('#hrAttendanceStatus').value,notes:$('#hrAttendanceNotes').value.trim()||null,created_by:session.user.id}).select('id').single()}
  if(x.id==='hrLeaveCreate'){sourceTable='hr_leave_requests';r=await supabase.from(sourceTable).insert({employee_id:$('#hrLeaveEmployee').value,leave_type:$('#hrLeaveType').value.trim(),start_date:$('#hrLeaveStart').value,end_date:$('#hrLeaveEnd').value,paid:$('#hrLeavePaid').value==='true',status:'DRAFT',reason:$('#hrLeaveReason').value.trim(),created_by:session.user.id}).select('id').single()}
  if(x.id==='hrDeductionCreate'){sourceTable='hr_compensation_items';r=await supabase.from(sourceTable).insert({employee_id:$('#hrDeductionEmployee').value,item_month:$('#hrDeductionMonth').value,item_type:$('#hrDeductionType').value,description:$('#hrDeductionDesc').value.trim(),amount_piasters:-Math.abs(Math.round(Number($('#hrDeductionAmount').value)*100)),status:'DRAFT',created_by:session.user.id}).select('id').single()}
  if(x.id==='hrCoverCreate'){sourceTable='hr_cover_assignments';r=await supabase.from(sourceTable).insert({employee_id:$('#hrCoverEmployee').value,cover_date:$('#hrCoverDate').value,period_count:Number($('#hrCoverPeriods').value),rate_piasters:Math.round(Number($('#hrCoverRate').value)*100),status:'DRAFT',notes:$('#hrCoverNotes').value.trim()||null,created_by:session.user.id}).select('id').single()}
  if(x.id==='hrCompensationCreate'){sourceTable='hr_compensation_items';r=await supabase.from(sourceTable).insert({employee_id:$('#hrCompEmployee').value,item_month:$('#hrCompMonth').value,item_type:$('#hrCompType').value,description:$('#hrCompDesc').value.trim(),amount_piasters:Math.round(Number($('#hrCompAmount').value)*100),status:'DRAFT',created_by:session.user.id}).select('id').single()}
  if(!r?.error&&sourceTable&&r.data?.id&&x.querySelector('.operation-files')?.files?.length){try{await saveAttachments(x.querySelector('.operation-files'),sourceTable,r.data.id)}catch(err){busy(x,false);return uiToast('حُفظت المسودة، لكن فشل رفع المرفق: '+err.message,'error',9000)}}
  await finish(r,x,'تم الحفظ بنجاح وظهر السجل في القائمة.');
 });

 // Administrator-only account policy: the public sign-up form is not a production entry point.
 const signupTab=$('#st');if(signupTab)signupTab.remove();const signupForm=$('#sf');if(signupForm)signupForm.remove();
 addTopChrome();
})();
