(()=>{
 const roles=['OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT','AUDITOR'];
 Object.assign(pages,{procurement:'المشتريات والموردون'});roles.forEach(r=>{access[r]||(access[r]=[]);if(!access[r].includes('procurement'))access[r].push('procurement')});
 const oldRenderProcurement=render,read=async(t,s='*')=>{const r=await supabase.from(t).select(s).order('created_at',{ascending:false}).range(0,999);if(r.error)throw r.error;return r.data||[]};
 const tabs=active=>'<div class="module-tabs">'+[['requisitions','طلبات الشراء'],['rfqs','RFQ والعروض'],['orders','أوامر الشراء'],['receipts','الاستلام'],['bills','فواتير الموردين'],['vendors','الموردون'],['returns','المرتجعات']].map(x=>'<button class="btn '+(active===x[0]?'on':'ghost')+'" onclick="showProcurement(\''+x[0]+'\')">'+x[1]+'</button>').join('')+'</div>';
 async function procurementPage(){if(!roles.includes(profile.role))return $('#content').innerHTML='<div class="msg err">غير مصرح.</div>';const [pr,po,gr,b,v,rfq,ret]=await Promise.all([read('purchase_requisitions'),read('purchase_orders','*,vendors(name)'),read('goods_receipts'),read('vendor_bills','*,vendors(name)'),read('vendors'),read('procurement_rfqs'),read('purchase_returns')]);window._proc={requisitions:pr,orders:po,receipts:gr,bills:b,vendors:v,rfqs:rfq,returns:ret};$('#content').innerHTML='<div class="grid cards">'+metric('طلبات الشراء',n(pr.length),'كل الحالات')+metric('أوامر الشراء',n(po.length),'')+metric('فواتير تحتاج مراجعة',n(b.filter(x=>!['MATCHED','EXCEPTION_APPROVED'].includes(x.match_status)).length),'Three-Way Match')+metric('الموردون النشطون',n(v.filter(x=>x.active).length),'','green')+'</div><div class="sec"><h3>دورة المشتريات والموردين</h3><input id="procSearch" placeholder="بحث في الجدول الحالي" oninput="showProcurement(window._procTab||\'requisitions\')"></div>'+tabs('requisitions')+'<div id="procHost"></div><div class="note">لا يتم ترحيل فاتورة أو دفعة قبل الاعتماد والمطابقة. لا يمكن دفع فاتورة غير POSTED أو غير MATCHED/EXCEPTION_APPROVED.</div>';showProcurement('requisitions')}
 const cfg={requisitions:{h:['رقم الطلب','التاريخ','القسم','الغرض','التقديري','الحالة'],k:['pr_number','request_date','department','purpose','estimated_total_piasters','status']},rfqs:{h:['RFQ','طلب الشراء','المهلة','العروض المطلوبة','الحالة','الاستثناء'],k:['rfq_number','requisition_id','response_due_at','required_quote_count','status','exception_reason']},orders:{h:['PO','المورد','التاريخ','الإجمالي','الحالة'],k:['po_number','vendors.name','order_date','total_piasters','status']},receipts:{h:['GRN','أمر الشراء','التاريخ','الحالة'],k:['grn_number','purchase_order_id','receipt_date','status']},bills:{h:['الفاتورة','المورد','فاتورة المورد','الإجمالي','المطابقة','الحالة'],k:['bill_number','vendors.name','supplier_invoice_number','total_piasters','match_status','status']},vendors:{h:['الكود','المورد','الضريبي','الهاتف','التصنيف','الحالة'],k:['vendor_code','name','tax_id','phone','category','active']},returns:{h:['رقم المرتجع','التاريخ','السبب','الحالة'],k:['return_number','return_date','reason','status']}};
 const val=(x,k)=>k.split('.').reduce((o,p)=>o?.[p],x),money=k=>['estimated_total_piasters','total_piasters'].includes(k);
 window.showProcurement=type=>{window._procTab=type;const q=($('#procSearch')?.value||'').toLocaleLowerCase('ar'),c=cfg[type],a=(window._proc?.[type]||[]).filter(x=>!q||JSON.stringify(x).toLocaleLowerCase('ar').includes(q));$('#procHost').innerHTML='<div class="tools"><button class="btn ghost" onclick="printTable()">طباعة / PDF</button><button class="btn ghost" onclick="downloadTableCSV()">CSV / Excel</button></div><div class="tablewrap"><table id="procTable" class="tbl"><thead><tr>'+c.h.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+(a.map(x=>'<tr onclick="openProcurementRecord(\''+type+'\',\''+x.id+'\')">'+c.k.map(k=>'<td>'+esc(money(k)?egp(val(x,k)):String(val(x,k)??'—'))+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="'+c.h.length+'">لا توجد بيانات.</td></tr>')+'</tbody></table></div>'};
 window.openProcurementRecord=(type,id)=>{const x=(window._proc?.[type]||[]).find(v=>v.id===id);if(!x)return;let actions='';if(type==='requisitions'&&x.status==='DRAFT')actions='<button class="btn primary" onclick="procRpc(\'submit_purchase_requisition\',\''+id+'\',\'p_id\')">إرسال</button>';if(type==='orders'&&x.status==='DRAFT')actions='<button class="btn primary" onclick="procRpc(\'submit_purchase_order\',\''+id+'\',\'p_id\')">إرسال</button>';if(type==='bills'&&x.status==='DRAFT')actions='<button class="btn ghost" onclick="procRpc(\'procurement_three_way_match\',\''+id+'\',\'p_bill\')">تشغيل المطابقة</button> <button class="btn primary" onclick="procRpc(\'submit_vendor_bill\',\''+id+'\',\'p_bill_id\')">إرسال</button>';openM('تفاصيل السجل','<div class="tablewrap"><table class="tbl"><tbody>'+Object.entries(x).filter(([k])=>!['id'].includes(k)).map(([k,v])=>'<tr><th>'+esc(k)+'</th><td>'+esc(typeof v==='object'?JSON.stringify(v):String(v??'—'))+'</td></tr>').join('')+'</tbody></table></div><div class="tools">'+actions+'<button class="btn ghost" onclick="printProcurementRecord(\''+type+'\',\''+id+'\')">طباعة</button></div>')};
 window.procRpc=async(fn,id,key)=>{const p={};p[key]=id;const r=await supabase.rpc(fn,p);if(r.error)return uiToast(r.error.message,'error',8000);closeM();uiToast('تم تنفيذ الإجراء وتسجيله.','success');await procurementPage()};
 window.printProcurementRecord=(type,id)=>{const x=(window._proc?.[type]||[]).find(v=>v.id===id);if(!x)return;const host=$('#printArea');host.innerHTML='<div class="print-report"><header><h1>Bradford School ERP</h1><h2>'+esc(pages.procurement)+'</h2></header><pre style="white-space:pre-wrap;direction:rtl">'+esc(JSON.stringify(x,null,2))+'</pre></div>';host.classList.remove('print-only');window.print();setTimeout(()=>{host.innerHTML='';host.classList.add('print-only')},300)};
 render=async function(){if(page==='procurement')return procurementPage();return oldRenderProcurement()};
})();
