-- Phase 4: asset lifecycle and cheque controls. No seed or existing-row updates.
create table if not exists public.asset_maintenance(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.fixed_assets(id),maintenance_type text not null check(maintenance_type in('PREVENTIVE','CORRECTIVE','WARRANTY','INSPECTION')),reported_at timestamptz not null default now(),scheduled_date date,completed_date date,vendor_id uuid references public.vendors(id),cost_piasters bigint not null default 0 check(cost_piasters>=0),status text not null default 'OPEN' check(status in('OPEN','SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')),description text not null,document_urls text[] not null default '{}',created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table if not exists public.asset_warranties(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.fixed_assets(id),provider text,start_date date,end_date date not null,policy_number text,terms text,document_urls text[] not null default '{}',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.asset_custody_events(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.fixed_assets(id),event_type text not null check(event_type in('ASSIGN','TRANSFER','RETURN','CLEARANCE')),event_date date not null,custodian_user_id uuid references auth.users(id),location text,condition_note text,document_urls text[] not null default '{}',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.asset_lifecycle_events(id bigint generated always as identity primary key,asset_id uuid not null references public.fixed_assets(id),event_type text not null check(event_type in('ACQUIRED','IN_SERVICE','TRANSFERRED','MAINTAINED','REVALUED','IMPAIRED','DISPOSED','MISSING','FOUND')),event_date date not null,old_data jsonb,new_data jsonb,reason text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.cheque_status_history(id bigint generated always as identity primary key,cheque_id uuid not null references public.cheques(id),from_status text,to_status text not null,reason text,bank_transaction_id uuid references public.bank_transactions(id),changed_at timestamptz not null default now(),changed_by uuid not null references auth.users(id));

do $$declare t text;begin foreach t in array array['asset_maintenance','asset_warranties','asset_custody_events','asset_lifecycle_events','cheque_status_history'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''TREASURY'',''AUDITOR''))',t||'_read',t);end loop;end$$;
grant insert,update on public.asset_maintenance,public.asset_warranties,public.asset_custody_events to authenticated;
create policy asset_maintenance_write on public.asset_maintenance for all to authenticated using(status in('OPEN','SCHEDULED','IN_PROGRESS') and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT')) with check(status in('OPEN','SCHEDULED','IN_PROGRESS') and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT'));
create policy asset_warranty_write on public.asset_warranties for all to authenticated using(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT')) with check(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT'));
create policy asset_custody_write on public.asset_custody_events for insert to authenticated with check(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT'));
revoke delete on public.fixed_assets,public.cheques,public.asset_transfers,public.asset_disposals,public.depreciation_runs,public.depreciation_run_lines from authenticated;

create or replace function private.asset_lifecycle_audit() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$begin if tg_op='INSERT' then insert into public.asset_lifecycle_events(asset_id,event_type,event_date,new_data,reason,created_by)values(new.id,'ACQUIRED',coalesce(new.purchase_date,current_date),to_jsonb(new),'Asset registered',auth.uid());elsif row(new.location,new.custodian_user_id,new.asset_status,new.accumulated_depreciation_piasters) is distinct from row(old.location,old.custodian_user_id,old.asset_status,old.accumulated_depreciation_piasters) then insert into public.asset_lifecycle_events(asset_id,event_type,event_date,old_data,new_data,reason,created_by)values(new.id,case when new.asset_status='DISPOSED' then 'DISPOSED' when new.location is distinct from old.location or new.custodian_user_id is distinct from old.custodian_user_id then 'TRANSFERRED' else 'REVALUED' end,current_date,jsonb_build_object('location',old.location,'custodian',old.custodian_user_id,'status',old.asset_status,'accumulated_depreciation',old.accumulated_depreciation_piasters),jsonb_build_object('location',new.location,'custodian',new.custodian_user_id,'status',new.asset_status,'accumulated_depreciation',new.accumulated_depreciation_piasters),'Controlled lifecycle update',auth.uid());end if;return new;end$$;
drop trigger if exists fixed_asset_lifecycle_audit on public.fixed_assets;create trigger fixed_asset_lifecycle_audit after insert or update on public.fixed_assets for each row execute function private.asset_lifecycle_audit();

create or replace function private.cheque_status_audit() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$begin if new.status is distinct from old.status then insert into public.cheque_status_history(cheque_id,from_status,to_status,reason,bank_transaction_id,changed_by)values(new.id,old.status,new.status,new.status_reason,new.bank_transaction_id,auth.uid());end if;return new;end$$;
drop trigger if exists cheque_status_audit on public.cheques;create trigger cheque_status_audit after update on public.cheques for each row execute function private.cheque_status_audit();
revoke all on function private.asset_lifecycle_audit(),private.cheque_status_audit() from public,anon,authenticated;

create or replace view public.v_asset_book_values with(security_invoker=true) as select a.*,greatest(0,a.acquisition_cost_piasters-a.accumulated_depreciation_piasters) book_value_piasters,case when a.useful_life_months is null or a.useful_life_months=0 then 0 else greatest(0,a.acquisition_cost_piasters-a.salvage_value_piasters)/a.useful_life_months end monthly_depreciation_piasters from public.fixed_assets a;
create or replace view public.v_cheque_due_alerts with(security_invoker=true) as select c.*,case when c.due_date<current_date and c.status in('OUTSTANDING','UNDER_COLLECTION') then 'OVERDUE' when c.due_date<=current_date+interval '7 days' and c.status in('OUTSTANDING','UNDER_COLLECTION') then 'DUE_SOON' else 'NORMAL' end alert_status from public.cheques c;
grant select on public.v_asset_book_values,public.v_cheque_due_alerts to authenticated;
