begin;
create table public.erp_organizations(id uuid primary key default gen_random_uuid(),organization_code text not null unique,organization_name text not null,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.erp_schools(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.erp_organizations(id),school_code text not null,school_name text not null,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(organization_id,school_code));
create table public.erp_branches(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.erp_schools(id),branch_code text not null,branch_name text not null,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(school_id,branch_code));
create table public.erp_divisions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.erp_schools(id),division_code text not null,division_name text not null,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(school_id,division_code));
create table public.erp_academic_years(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.erp_organizations(id),year_code text not null,start_date date,end_date date,status text not null default 'ACTIVE' check(status in('PLANNED','ACTIVE','CLOSED')),created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(organization_id,year_code),check(end_date is null or start_date is null or end_date>=start_date));
create table public.erp_user_scopes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),organization_id uuid not null references public.erp_organizations(id),school_id uuid references public.erp_schools(id),branch_id uuid references public.erp_branches(id),division_id uuid references public.erp_divisions(id),department_id uuid references public.departments(id),cost_center_id uuid references public.cost_centers(id),active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create unique index erp_user_scope_uq on public.erp_user_scopes(user_id,organization_id,coalesce(school_id,'00000000-0000-0000-0000-000000000000'),coalesce(branch_id,'00000000-0000-0000-0000-000000000000'),coalesce(division_id,'00000000-0000-0000-0000-000000000000'),coalesce(department_id,'00000000-0000-0000-0000-000000000000'),coalesce(cost_center_id,'00000000-0000-0000-0000-000000000000'));
alter table public.erp_organizations enable row level security;alter table public.erp_schools enable row level security;alter table public.erp_branches enable row level security;alter table public.erp_divisions enable row level security;alter table public.erp_academic_years enable row level security;alter table public.erp_user_scopes enable row level security;
revoke all on public.erp_organizations,public.erp_schools,public.erp_branches,public.erp_divisions,public.erp_academic_years,public.erp_user_scopes from anon,authenticated;grant select on public.erp_organizations,public.erp_schools,public.erp_branches,public.erp_divisions,public.erp_academic_years,public.erp_user_scopes to authenticated;grant insert,update on public.erp_organizations,public.erp_schools,public.erp_branches,public.erp_divisions,public.erp_academic_years,public.erp_user_scopes to authenticated;

insert into public.erp_organizations(organization_code,organization_name)values('MCIS','Mid Cairo International School')on conflict(organization_code)do nothing;
insert into public.erp_schools(organization_id,school_code,school_name)select id,'MCIS','Mid Cairo International School' from public.erp_organizations where organization_code='MCIS' on conflict(organization_id,school_code)do nothing;
insert into public.erp_branches(school_id,branch_code,branch_name)select id,'MAIN','Main Campus' from public.erp_schools where school_code='MCIS' on conflict(school_id,branch_code)do nothing;
insert into public.erp_divisions(school_id,division_code,division_name)select id,x.code,x.name from public.erp_schools cross join(values('AMERICAN','American'),('IG','British / IG'),('ADMINISTRATION','Administration'))x(code,name)where school_code='MCIS' on conflict(school_id,division_code)do nothing;
insert into public.erp_academic_years(organization_id,year_code,status)select id,'2026-2027','ACTIVE' from public.erp_organizations where organization_code='MCIS' on conflict(organization_id,year_code)do nothing;
insert into public.erp_user_scopes(user_id,organization_id)select p.user_id,o.id from public.user_profiles p cross join public.erp_organizations o where p.active and o.organization_code='MCIS' on conflict do nothing;

create or replace function public.default_organization_id() returns uuid language sql stable security definer set search_path='' as $$select id from public.erp_organizations where organization_code='MCIS' and active limit 1$$;
create or replace function public.can_access_organization(p_organization uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.erp_user_scopes s where s.user_id=auth.uid() and s.organization_id=p_organization and s.active)$$;
revoke all on function public.default_organization_id(),public.can_access_organization(uuid) from public,anon;grant execute on function public.default_organization_id(),public.can_access_organization(uuid) to authenticated;
create policy erp_org_read on public.erp_organizations for select to authenticated using(public.can_access_organization(id));
create policy erp_school_read on public.erp_schools for select to authenticated using(public.can_access_organization(organization_id));
create policy erp_branch_read on public.erp_branches for select to authenticated using(exists(select 1 from public.erp_schools s where s.id=school_id and public.can_access_organization(s.organization_id)));
create policy erp_division_read on public.erp_divisions for select to authenticated using(exists(select 1 from public.erp_schools s where s.id=school_id and public.can_access_organization(s.organization_id)));
create policy erp_year_read on public.erp_academic_years for select to authenticated using(public.can_access_organization(organization_id));
create policy erp_scope_self_read on public.erp_user_scopes for select to authenticated using(user_id=(select auth.uid()) or public.current_finance_role()='OWNER');
create policy erp_master_owner_write on public.erp_organizations for all to authenticated using(public.current_finance_role()='OWNER') with check(public.current_finance_role()='OWNER');
create policy erp_school_owner_write on public.erp_schools for all to authenticated using(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id)) with check(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id));
create policy erp_year_owner_write on public.erp_academic_years for all to authenticated using(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id)) with check(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id));
create policy erp_scope_owner_write on public.erp_user_scopes for all to authenticated using(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id)) with check(public.current_finance_role()='OWNER' and public.can_access_organization(organization_id));

do $$declare t text;oid uuid:=public.default_organization_id();begin foreach t in array array['students','student_accounts','student_charges','student_payments','expenses','treasury_transactions','bank_accounts','bank_transactions','fixed_assets','vendors','purchase_requisitions','purchase_orders','vendor_bills','inventory_warehouses','inventory_items','inventory_movements','transport_routes','transport_vehicles','transport_enrollments','hr_employees','payroll_runs','journal_entries'] loop if to_regclass('public.'||t) is not null then execute format('alter table public.%I add column if not exists organization_id uuid references public.erp_organizations(id)',t);execute format('alter table public.%I disable trigger user',t);execute format('update public.%I set organization_id=$1 where organization_id is null',t)using oid;execute format('alter table public.%I enable trigger user',t);execute format('alter table public.%I alter column organization_id set default public.default_organization_id()',t);execute format('alter table public.%I alter column organization_id set not null',t);execute format('create policy %I on public.%I as restrictive for all to authenticated using(public.can_access_organization(organization_id)) with check(public.can_access_organization(organization_id))','tenant_scope_'||t,t);end if;end loop;end$$;
create or replace function private.enforce_organization_scope() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$begin if new.organization_id is null then new.organization_id:=public.default_organization_id();end if;if auth.uid() is not null and not public.can_access_organization(new.organization_id) then raise exception 'Organization scope denied';end if;return new;end$$;
do $$declare t text;begin foreach t in array array['students','student_accounts','student_charges','student_payments','expenses','treasury_transactions','bank_accounts','bank_transactions','fixed_assets','vendors','purchase_requisitions','purchase_orders','vendor_bills','inventory_warehouses','inventory_items','inventory_movements','transport_routes','transport_vehicles','transport_enrollments','hr_employees','payroll_runs','journal_entries'] loop if to_regclass('public.'||t) is not null then execute format('create trigger %I before insert or update of organization_id on public.%I for each row execute function private.enforce_organization_scope()','enforce_org_'||t,t);end if;end loop;end$$;
revoke all on function private.enforce_organization_scope() from public,anon,authenticated;
insert into public.audit_events(table_name,record_id,action,new_data,metadata)select 'erp_organizations',id::text,'MCIS_SCOPE_BACKFILL',jsonb_build_object('organization_code',organization_code),jsonb_build_object('existing_users_scoped',true,'financial_values_changed',false)from public.erp_organizations where organization_code='MCIS';
commit;
