begin;

-- Phase 5 transport operations. Additive only; no production rows are changed or seeded.
create table public.transport_route_stops(id uuid primary key default gen_random_uuid(),route_id uuid not null references public.transport_routes(id),stop_code text not null,stop_name text not null,sequence_no integer not null check(sequence_no>0),pickup_time time,dropoff_time time,latitude numeric(9,6),longitude numeric(9,6),status text not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE')),created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),unique(route_id,stop_code),unique(route_id,sequence_no));
create table public.transport_vehicle_documents(id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.transport_vehicles(id),document_type text not null check(document_type in('LICENSE','INSURANCE','INSPECTION','REGISTRATION','OTHER')),document_number text,issued_on date,expires_on date,file_path text,status text not null default 'ACTIVE' check(status in('ACTIVE','EXPIRED','RENEWED','CANCELLED')),created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.transport_trips(id uuid primary key default gen_random_uuid(),route_id uuid not null references public.transport_routes(id),vehicle_id uuid not null references public.transport_vehicles(id),driver_id uuid references public.transport_staff(id),supervisor_id uuid references public.transport_staff(id),trip_date date not null,direction text not null check(direction in('OUTBOUND','RETURN')),scheduled_at timestamptz,started_at timestamptz,completed_at timestamptz,status text not null default 'PLANNED' check(status in('PLANNED','BOARDING','IN_PROGRESS','COMPLETED','CANCELLED')),notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.transport_trip_attendance(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.transport_trips(id),enrollment_id uuid not null references public.transport_enrollments(id),boarding_status text not null default 'EXPECTED' check(boarding_status in('EXPECTED','BOARDED','ABSENT','EXCUSED')),boarded_at timestamptz,boarded_stop_id uuid references public.transport_route_stops(id),alighting_status text not null default 'EXPECTED' check(alighting_status in('EXPECTED','ALIGHTED','NOT_RECORDED')),alighted_at timestamptz,alighted_stop_id uuid references public.transport_route_stops(id),notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),unique(trip_id,enrollment_id));
create table public.transport_temporary_changes(id uuid primary key default gen_random_uuid(),enrollment_id uuid not null references public.transport_enrollments(id),effective_date date not null,temporary_route_id uuid references public.transport_routes(id),temporary_vehicle_id uuid references public.transport_vehicles(id),temporary_stop_id uuid references public.transport_route_stops(id),reason text not null,status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','REJECTED','CANCELLED')),approved_at timestamptz,approved_by uuid references auth.users(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.transport_vehicle_maintenance(id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.transport_vehicles(id),maintenance_type text not null,opened_on date not null,completed_on date,odometer_km numeric(12,2),vendor_id uuid references public.vendors(id),cost_piasters bigint not null default 0 check(cost_piasters>=0),document_path text,status text not null default 'OPEN' check(status in('OPEN','COMPLETED','CANCELLED')),notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.transport_fuel_logs(id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.transport_vehicles(id),fuel_date date not null,litres numeric(12,3) not null check(litres>0),odometer_km numeric(12,2),amount_piasters bigint not null check(amount_piasters>=0),vendor_id uuid references public.vendors(id),receipt_reference text,document_path text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.transport_incidents(id uuid primary key default gen_random_uuid(),vehicle_id uuid references public.transport_vehicles(id),trip_id uuid references public.transport_trips(id),incident_at timestamptz not null,incident_type text not null,description text not null,injuries_reported boolean not null default false,authority_reference text,document_path text,status text not null default 'OPEN' check(status in('OPEN','UNDER_REVIEW','CLOSED')),closed_at timestamptz,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.transport_integration_endpoints(id uuid primary key default gen_random_uuid(),provider_code text not null unique,display_name text not null,adapter_mode text not null default 'DISABLED' check(adapter_mode in('DISABLED','SANDBOX','PRODUCTION')),base_url text,secret_reference text,enabled boolean not null default false,last_health_at timestamptz,last_health_status text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),check(secret_reference is null or secret_reference !~* '(token|password|secret)=|^[A-Za-z0-9+/]{32,}={0,2}$'));

do $$declare t text;begin foreach t in array array['transport_route_stops','transport_vehicle_documents','transport_trips','transport_trip_attendance','transport_temporary_changes','transport_vehicle_maintenance','transport_fuel_logs','transport_incidents','transport_integration_endpoints'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select,insert,update on public.%I to authenticated',t);execute format('create policy %I on public.%I for select to authenticated using (public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''TREASURY'',''ADMISSION'',''AUDITOR''))',t||'_read',t);execute format('create policy %I on public.%I for insert to authenticated with check (public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''ADMISSION'') and created_by=(select auth.uid()))',t||'_insert',t);if t<>'transport_fuel_logs' then execute format('create policy %I on public.%I for update to authenticated using (public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''ADMISSION'')) with check (public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''ADMISSION'') and updated_by=(select auth.uid()))',t||'_update',t);end if;end loop;end$$;

create index transport_trips_date_idx on public.transport_trips(trip_date,status);
create index transport_attendance_trip_idx on public.transport_trip_attendance(trip_id,boarding_status,alighting_status);
create index transport_documents_expiry_idx on public.transport_vehicle_documents(expires_on,status);
create index transport_maintenance_vehicle_idx on public.transport_vehicle_maintenance(vehicle_id,opened_on desc);
create index transport_fuel_vehicle_idx on public.transport_fuel_logs(vehicle_id,fuel_date desc);

create or replace view public.v_transport_route_occupancy with(security_invoker=true) as select r.id route_id,r.route_code,r.route_name,r.academic_year,v.id vehicle_id,v.vehicle_code,v.capacity,count(e.id) filter(where e.status='ACTIVE') active_enrollments,greatest(v.capacity-count(e.id) filter(where e.status='ACTIVE'),0) available_seats,(count(e.id) filter(where e.status='ACTIVE')>v.capacity) over_capacity from public.transport_routes r left join public.transport_vehicles v on v.route_id=r.id and v.status='ACTIVE' left join public.transport_enrollments e on e.route_id=r.id and e.vehicle_id=v.id group by r.id,v.id;
create or replace view public.v_transport_expiry_alerts with(security_invoker=true) as select d.id,d.vehicle_id,v.vehicle_code,d.document_type,d.document_number,d.expires_on,case when d.expires_on<current_date then 'EXPIRED' when d.expires_on<=current_date+30 then 'DUE_SOON' else 'VALID' end alert_status from public.transport_vehicle_documents d join public.transport_vehicles v on v.id=d.vehicle_id where d.status='ACTIVE' and d.expires_on is not null;
grant select on public.v_transport_route_occupancy,public.v_transport_expiry_alerts to authenticated;

create or replace function private.transport_audit() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$begin insert into public.audit_events(table_name,record_id,action,old_data,new_data,changed_by)values(tg_table_name,coalesce(new.id,old.id)::text,tg_op,case when tg_op='INSERT' then null else to_jsonb(old) end,case when tg_op='DELETE' then null else to_jsonb(new) end,auth.uid());return coalesce(new,old);end$$;
do $$declare t text;begin foreach t in array array['transport_route_stops','transport_vehicle_documents','transport_trips','transport_trip_attendance','transport_temporary_changes','transport_vehicle_maintenance','transport_fuel_logs','transport_incidents','transport_integration_endpoints'] loop execute format('create trigger %I after insert or update on public.%I for each row execute function private.transport_audit()',t||'_audit',t);end loop;end$$;
revoke delete on public.transport_routes,public.transport_vehicles,public.transport_staff,public.transport_enrollments from authenticated;
comment on table public.transport_integration_endpoints is 'Provider-neutral future GPS/parent-app configuration. Credentials are secret references only; no live GPS is claimed.';
commit;
