begin;
alter table public.payroll_lines add column if not exists employee_code_snapshot text;
alter table public.payroll_lines add column if not exists employee_name_snapshot text;
create or replace function private.hr_line_snapshot() returns trigger language plpgsql security definer set search_path='' as $$begin select employee_code,full_name into new.employee_code_snapshot,new.employee_name_snapshot from public.hr_employees where id=new.employee_id;if new.employee_code_snapshot is null then raise exception 'Employee not found';end if;return new;end$$;
drop trigger if exists hr_line_snapshot on public.payroll_lines;create trigger hr_line_snapshot before insert on public.payroll_lines for each row execute function private.hr_line_snapshot();
alter table public.payroll_lines alter column employee_code_snapshot set not null;alter table public.payroll_lines alter column employee_name_snapshot set not null;
create or replace function private.hr_post_journal(p_run uuid,p_kind text,p_payment_method text default null) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$declare r public.payroll_runs%rowtype;jid uuid;cash_code text;begin select * into r from public.payroll_runs where id=p_run;if not found or r.net_pay_piasters<=0 then raise exception 'Payroll net amount must be positive';end if;if p_kind='ACCRUAL' then insert into public.journal_entries(transaction_date,description,source_module,source_id,status,created_by)values(r.payroll_month,'Payroll accrual '||to_char(r.payroll_month,'YYYY-MM'),'payroll_runs',r.id,'DRAFT',auth.uid())returning id into jid;insert into public.journal_lines(entry_id,line_no,account_code,debit_piasters,credit_piasters,description,cost_center_id)values(jid,1,'5100',r.net_pay_piasters,0,'Payroll expense',r.cost_center_id),(jid,2,'2400',0,r.net_pay_piasters,'Payroll payable',r.cost_center_id);elsif p_kind='PAYMENT' then cash_code:=case when p_payment_method='CASH' then '1100' else '1200' end;insert into public.journal_entries(transaction_date,description,source_module,source_id,status,created_by)values(current_date,'Payroll payment '||to_char(r.payroll_month,'YYYY-MM'),'payroll_payments',r.id,'DRAFT',auth.uid())returning id into jid;insert into public.journal_lines(entry_id,line_no,account_code,debit_piasters,credit_piasters,description,cost_center_id)values(jid,1,'2400',r.net_pay_piasters,0,'Settle payroll payable',r.cost_center_id),(jid,2,cash_code,0,r.net_pay_piasters,'Payroll payment',r.cost_center_id);else raise exception 'Unsupported payroll journal kind';end if;perform set_config('bradford.workflow','1',true);update public.journal_entries set status='POSTED',posted_at=now(),posted_by=auth.uid() where id=jid;return jid;end$$;
revoke all on function private.hr_line_snapshot(),private.hr_post_journal(uuid,text,text) from public,anon,authenticated;
commit;
