-- Phase 1: additive Admissions and Student Administration foundation.
-- No existing student or financial row is updated by this migration.
alter type public.finance_role add value if not exists 'ADMISSIONS_REVIEWER';
alter type public.finance_role add value if not exists 'ADMISSIONS_APPROVER';

create sequence if not exists public.admission_application_number_seq;
create table if not exists public.admission_applications(
 id uuid primary key default gen_random_uuid(),
 application_number text not null unique default ('APP-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.admission_application_number_seq')::text,6,'0')),
 idempotency_key text unique,
 academic_year text not null,requested_grade text not null,division text not null check(division in('AMERICAN','BRITISH')),
 student_name text not null,gender text,birth_date date not null,nationality text,national_id text,passport_number text,previous_school text,
 primary_phone text not null,email text,address text,
 status text not null default 'DRAFT' check(status in('DRAFT','SUBMITTED','DOCUMENTS_REVIEW','ASSESSMENT_SCHEDULED','ASSESSED','WAITING_LIST','ACCEPTED','REJECTED','ENROLLED','WITHDRAWN')),
 status_reason text,document_status text not null default 'MISSING' check(document_status in('COMPLETE','MISSING','NEEDS_REVIEW')),
 assigned_to uuid references auth.users(id),version integer not null default 1,
 enrolled_student_id uuid references public.students(id),enrolled_account_id uuid references public.student_accounts(id),
 submitted_at timestamptz,decided_at timestamptz,decided_by uuid references auth.users(id),enrolled_at timestamptz,enrolled_by uuid references auth.users(id),
 created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),
 check(national_id is not null or passport_number is not null)
);
create unique index if not exists admission_national_id_uq on public.admission_applications(lower(btrim(national_id))) where national_id is not null;
create unique index if not exists admission_passport_uq on public.admission_applications(lower(btrim(passport_number))) where passport_number is not null;
create index if not exists admission_probable_duplicate_idx on public.admission_applications(lower(btrim(student_name)),birth_date,primary_phone);

create table if not exists public.admission_guardians(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.admission_applications(id) on delete cascade,guardian_type text not null check(guardian_type in('FATHER','MOTHER','GUARDIAN')),full_name text not null,phone text not null,alternate_phone text,email text,national_id text,address text,authorized_contact boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(application_id,guardian_type));
create table if not exists public.admission_documents(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.admission_applications(id) on delete cascade,document_type text not null,bucket_id text not null default 'admission-documents',object_path text not null unique,original_filename text,mime_type text,size_bytes bigint,sha256 text,review_status text not null default 'MISSING' check(review_status in('COMPLETE','MISSING','NEEDS_REVIEW')),review_note text,reviewed_at timestamptz,reviewed_by uuid references auth.users(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.admission_appointments(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.admission_applications(id),appointment_type text not null check(appointment_type in('ASSESSMENT','INTERVIEW')),scheduled_at timestamptz not null,duration_minutes integer not null default 30 check(duration_minutes between 5 and 480),status text not null default 'SCHEDULED' check(status in('SCHEDULED','ATTENDED','MISSED','CANCELLED','RESCHEDULED')),notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.admission_assessments(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.admission_applications(id),academic_score numeric,behavioral_score numeric,interview_score numeric,recommendation text,confidential_notes text,assessed_at timestamptz not null default now(),assessed_by uuid not null references auth.users(id),unique(application_id,assessed_by,assessed_at));
create table if not exists public.admission_reviews(id bigint generated always as identity primary key,application_id uuid not null references public.admission_applications(id),from_status text,to_status text not null,reason text,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id));
create table if not exists public.admission_duplicate_candidates(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.admission_applications(id),candidate_application_id uuid references public.admission_applications(id),candidate_student_id uuid references public.students(id),match_type text not null,score numeric,evidence jsonb not null default '{}',status text not null default 'OPEN' check(status in('OPEN','CONFIRMED','DISMISSED')),resolved_at timestamptz,resolved_by uuid references auth.users(id),resolution_note text,check(candidate_application_id is not null or candidate_student_id is not null));

create table if not exists public.academic_classes(id uuid primary key default gen_random_uuid(),academic_year text not null,division text not null,grade text not null,class_name text not null,capacity integer not null check(capacity>0),active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(academic_year,division,grade,class_name));
create table if not exists public.student_families(id uuid primary key default gen_random_uuid(),family_code text not null unique,display_name text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.student_family_members(family_id uuid not null references public.student_families(id),student_id uuid not null references public.students(id),relationship text not null default 'CHILD',primary key(family_id,student_id));
create table if not exists public.student_contacts(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),contact_type text not null,full_name text not null,phone text,email text,address text,valid_from date not null default current_date,valid_to date,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.student_enrollments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),academic_year text not null,division text not null,grade text not null,class_id uuid references public.academic_classes(id),status text not null default 'ACTIVE' check(status in('ACTIVE','WITHDRAWN','SUSPENDED','GRADUATED','PROMOTED')),source_application_id uuid references public.admission_applications(id),started_at date not null default current_date,ended_at date,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(student_id,academic_year));
create table if not exists public.student_services(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),academic_year text not null,service_type text not null check(service_type in('EDUCATION','BOOKS','UNIFORM','TRANSPORT','ACTIVITY')),status text not null default 'ACTIVE',charge_id uuid references public.student_charges(id),starts_on date not null default current_date,ends_on date,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table if not exists public.student_status_history(id bigint generated always as identity primary key,student_id uuid not null references public.students(id),from_status text,to_status text not null,reason text,changed_at timestamptz not null default now(),changed_by uuid not null references auth.users(id));

do $$declare t text;begin foreach t in array array['admission_applications','admission_guardians','admission_documents','admission_appointments','admission_assessments','admission_reviews','admission_duplicate_candidates','academic_classes','student_families','student_family_members','student_contacts','student_enrollments','student_services','student_status_history'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
grant insert,update on public.admission_applications,public.admission_guardians,public.admission_documents,public.admission_appointments,public.admission_assessments to authenticated;
grant usage,select on sequence public.admission_application_number_seq to authenticated;

create or replace function private.is_admissions_reader() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.user_profiles p where p.user_id=auth.uid() and p.active and p.role::text in('OWNER','CEO','ADMISSION','ADMISSIONS_REVIEWER','ADMISSIONS_APPROVER'))$$;
revoke all on function private.is_admissions_reader() from public,anon,authenticated;
create policy admissions_read on public.admission_applications for select to authenticated using(private.is_admissions_reader());
create policy admissions_entry_insert on public.admission_applications for insert to authenticated with check(public.current_finance_role()::text in('ADMISSION','OWNER'));
create policy admissions_entry_update on public.admission_applications for update to authenticated using(status='DRAFT' and public.current_finance_role()::text in('ADMISSION','OWNER')) with check(status='DRAFT' and public.current_finance_role()::text in('ADMISSION','OWNER'));
do $$declare t text;begin foreach t in array array['admission_guardians','admission_documents','admission_appointments','admission_assessments','admission_reviews','admission_duplicate_candidates','academic_classes','student_families','student_family_members','student_contacts','student_enrollments','student_services','student_status_history'] loop execute format('create policy %I on public.%I for select to authenticated using(private.is_admissions_reader())',t||'_read',t);end loop;end$$;

create or replace function public.transition_admission(p_application uuid,p_to text,p_reason text default null) returns void language plpgsql security definer set search_path='public','private','pg_temp' as $$declare a public.admission_applications%rowtype;r text:=public.current_finance_role()::text;ok boolean:=false;begin if auth.uid() is null then raise exception 'Authentication required';end if;select * into a from public.admission_applications where id=p_application for update;if not found then raise exception 'Application not found';end if;ok:=(a.status='DRAFT' and p_to='SUBMITTED' and r in('ADMISSION','OWNER')) or (a.status='SUBMITTED' and p_to='DOCUMENTS_REVIEW' and r in('ADMISSIONS_REVIEWER','OWNER')) or (a.status='DOCUMENTS_REVIEW' and p_to='ASSESSMENT_SCHEDULED' and r in('ADMISSIONS_REVIEWER','OWNER')) or (a.status='ASSESSMENT_SCHEDULED' and p_to='ASSESSED' and r in('ADMISSIONS_REVIEWER','OWNER')) or (a.status='ASSESSED' and p_to in('WAITING_LIST','ACCEPTED','REJECTED') and r in('ADMISSIONS_APPROVER','OWNER')) or (p_to='WITHDRAWN' and a.status not in('ENROLLED','WITHDRAWN') and r in('ADMISSION','ADMISSIONS_APPROVER','OWNER'));if not ok then raise exception 'Invalid or unauthorized transition';end if;if p_to in('WAITING_LIST','REJECTED','WITHDRAWN') and length(btrim(coalesce(p_reason,'')))<3 then raise exception 'Reason required';end if;update public.admission_applications set status=p_to,status_reason=p_reason,submitted_at=case when p_to='SUBMITTED' then now() else submitted_at end,decided_at=case when p_to in('WAITING_LIST','ACCEPTED','REJECTED') then now() else decided_at end,decided_by=case when p_to in('WAITING_LIST','ACCEPTED','REJECTED') then auth.uid() else decided_by end,version=version+1,updated_at=now(),updated_by=auth.uid() where id=p_application;insert into public.admission_reviews(application_id,from_status,to_status,reason,created_by)values(p_application,a.status,p_to,p_reason,auth.uid());insert into public.audit_events(table_name,record_id,action,old_data,new_data,changed_by)values('admission_applications',p_application::text,'TRANSITION',jsonb_build_object('status',a.status),jsonb_build_object('status',p_to,'reason',p_reason),auth.uid());end$$;
revoke all on function public.transition_admission(uuid,text,text) from public,anon;grant execute on function public.transition_admission(uuid,text,text) to authenticated;

create or replace function public.enroll_admission_application(p_application uuid,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$declare a public.admission_applications%rowtype;s uuid;acct uuid;occupied integer;begin if public.current_finance_role()::text not in('ADMISSIONS_APPROVER','OWNER') then raise exception 'Not authorized';end if;select * into a from public.admission_applications where id=p_application for update;if a.status='ENROLLED' then return a.enrolled_student_id;end if;if a.status<>'ACCEPTED' then raise exception 'Application must be accepted';end if;if nullif(btrim(p_idempotency_key),'') is null then raise exception 'Idempotency key required';end if;if exists(select 1 from public.students x where (a.national_id is not null and lower(btrim(x.national_id))=lower(btrim(a.national_id))) or (lower(btrim(x.student_name))=lower(btrim(a.student_name)) and a.birth_date is not null and exists(select 1 from public.admission_duplicate_candidates d where d.application_id=a.id and d.candidate_student_id=x.id and d.status='OPEN'))) then raise exception 'Duplicate student requires resolution';end if;insert into public.students(student_code,student_name,grade,status,national_id,student_phone,student_email,address,section,created_by,updated_by)values(a.application_number,a.student_name,a.requested_grade,'ACTIVE',a.national_id,a.primary_phone,a.email,a.address,a.division,auth.uid(),auth.uid()) returning id into s;insert into public.student_accounts(student_id,academic_year,division_code,source_external_id,source_meta,created_by,updated_by)values(s,a.academic_year,case when a.division='BRITISH' then 'IG' else 'AMERICAN' end,'ADMISSION:'||a.id,jsonb_build_object('idempotency_key',p_idempotency_key),auth.uid(),auth.uid()) returning id into acct;insert into public.student_enrollments(student_id,academic_year,division,grade,source_application_id,created_by)values(s,a.academic_year,a.division,a.requested_grade,a.id,auth.uid());insert into public.student_status_history(student_id,to_status,reason,changed_by)values(s,'ACTIVE','Admissions enrollment',auth.uid());update public.admission_applications set status='ENROLLED',enrolled_student_id=s,enrolled_account_id=acct,enrolled_at=now(),enrolled_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=a.id;insert into public.admission_reviews(application_id,from_status,to_status,reason,created_by)values(a.id,'ACCEPTED','ENROLLED','Approved enrollment',auth.uid());insert into public.audit_events(table_name,record_id,action,new_data,changed_by,metadata)values('admission_applications',a.id::text,'ENROLL',jsonb_build_object('student_id',s,'account_id',acct),auth.uid(),jsonb_build_object('idempotency_key',p_idempotency_key,'financial_defaults','ZERO'));return s;end$$;
revoke all on function public.enroll_admission_application(uuid,text) from public,anon;grant execute on function public.enroll_admission_application(uuid,text) to authenticated;

comment on function public.enroll_admission_application(uuid,text) is 'Creates student/account with zero financial defaults. Approved fees must be added separately; no amounts are invented.';
