begin;

create table public.hr_approval_authorities(
 stage text primary key check(stage in ('HR_MANAGER','AMANY_FINAL','PAYMENT')),
 authority_name text not null, authority_email text not null, authority_user_id uuid references auth.users(id),
 active boolean not null default true, linked_at timestamptz, linked_by uuid references auth.users(id), updated_at timestamptz not null default now()
);
insert into public.hr_approval_authorities(stage,authority_name,authority_email,authority_user_id,active,linked_at)
values
 ('HR_MANAGER','Rehab','rehab@midcairointernationalschool.com',(select id from auth.users where lower(email)=lower('rehab@midcairointernationalschool.com')),true,now()),
 ('AMANY_FINAL','Dr. Amany Hussein','amanyhussienelz@gmail.com',(select id from auth.users where lower(email)=lower('amanyhussienelz@gmail.com')),true,now()),
 ('PAYMENT','Mahmoud','Mahmoudelsaid69000@gmail.com',(select id from auth.users where lower(email)=lower('Mahmoudelsaid69000@gmail.com')),true,now());

insert into public.user_profiles(user_id,full_name,role,active)
select id,'Rehab - HR Manager','HR_MANAGER'::public.finance_role,true from auth.users where lower(email)=lower('rehab@midcairointernationalschool.com')
on conflict(user_id) do update set role=excluded.role,full_name=excluded.full_name,active=true,updated_at=now();
insert into public.user_profiles(user_id,full_name,role,active)
select id,'Mariana - HR Officer','HR_OFFICER'::public.finance_role,true from auth.users where lower(email)=lower('Mariananadysmsm@gmail.com')
on conflict(user_id) do update set role=excluded.role,full_name=excluded.full_name,active=true,updated_at=now();
insert into public.user_profiles(user_id,full_name,role,active)
select id,'Mahmoud - Payroll Cashier','PAYROLL_CASHIER'::public.finance_role,true from auth.users where lower(email)=lower('Mahmoudelsaid69000@gmail.com')
on conflict(user_id) do update set role=excluded.role,full_name=excluded.full_name,active=true,updated_at=now();

create table public.hr_employees(
 id uuid primary key default gen_random_uuid(), employee_code text not null unique, full_name text not null,
 national_id text unique, birth_date date, phone text, email text, address text, department text, job_title text,
 direct_manager text, contract_type text, hire_date date, contract_end_date date, probation_end_date date,
 status text not null default 'ACTIVE' check(status in ('ACTIVE','ON_LEAVE','SUSPENDED','TERMINATED')),
 school_division text not null default 'ADMINISTRATION' check(school_division in ('AMERICAN','IG','ADMINISTRATION')),
 cost_center_id uuid references public.cost_centers(id), payment_method text check(payment_method in ('CASH','BANK','OTHER')),
 bank_name text, bank_account_name text, bank_account_number text, bank_iban text, social_insurance_number text,
 qualification text, experience_years numeric(5,2) check(experience_years is null or experience_years>=0),
 teaching_subjects text[], teaching_grades text[], notes text,
 created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id)
);
create table public.hr_employee_documents(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),document_type text not null,document_url text not null,expiry_date date,verified boolean not null default false,notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_attendance(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),work_date date not null,check_in time,check_out time,late_minutes integer not null default 0,early_leave_minutes integer not null default 0,status text not null default 'PRESENT',notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(employee_id,work_date));
create table public.hr_leave_requests(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),leave_type text not null,start_date date not null,end_date date not null,paid boolean not null default true,status text not null default 'DRAFT',reason text,review_note text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_cover_assignments(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),cover_date date not null,period_count numeric(8,2) not null default 1,rate_piasters bigint not null default 0,status text not null default 'DRAFT',notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_compensation_items(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),item_month date not null,item_type text not null check(item_type in ('ALLOWANCE','BONUS','COMMISSION','DEDUCTION','PENALTY','ADJUSTMENT')),description text not null,amount_piasters bigint not null check(amount_piasters>=0),status text not null default 'DRAFT',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_employee_loans(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),loan_type text not null check(loan_type in ('ADVANCE','LOAN')),principal_piasters bigint not null check(principal_piasters>0),installment_piasters bigint not null default 0,outstanding_piasters bigint not null check(outstanding_piasters>=0),status text not null default 'DRAFT',start_month date,notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_employee_requests(id uuid primary key default gen_random_uuid(),employee_id uuid references public.hr_employees(id),request_type text not null,subject text not null,details text,status text not null default 'DRAFT',response text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_applicants(id uuid primary key default gen_random_uuid(),full_name text not null,email text,phone text,position_applied text,status text not null default 'NEW',cv_url text,notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_onboarding_tasks(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),task_name text not null,due_date date,status text not null default 'OPEN',probation_review boolean not null default false,notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_performance_reviews(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),review_date date not null,review_type text not null,rating numeric(4,2),classroom_notes text,strengths text,improvements text,status text not null default 'DRAFT',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_training_records(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),training_name text not null,provider text,start_date date,end_date date,certificate_url text,expiry_date date,status text not null default 'PLANNED',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_grievances(id uuid primary key default gen_random_uuid(),employee_id uuid references public.hr_employees(id),case_type text not null check(case_type in ('COMPLAINT','INVESTIGATION','APPEAL')),subject text not null,details text,status text not null default 'OPEN',confidential boolean not null default true,resolution text,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_custody_clearance(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),item_name text not null,serial_number text,assigned_at date,returned_at date,condition_note text,clearance_status text not null default 'ASSIGNED',created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_terminations(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hr_employees(id),termination_date date not null,termination_type text not null,reason text,notice_end_date date,clearance_complete boolean not null default false,final_settlement_piasters bigint,status text not null default 'DRAFT',created_at timestamptz not null default now(),created_by uuid references auth.users(id));

create table public.payroll_runs(
 id uuid primary key default gen_random_uuid(),payroll_month date not null,division text not null check(division in ('AMERICAN','IG','ADMINISTRATION','ALL')),cost_center_id uuid references public.cost_centers(id),
 status text not null default 'DRAFT' check(status in ('DRAFT','SUBMITTED_TO_HR_MANAGER','HR_MANAGER_APPROVED','AMANY_APPROVED','READY_FOR_PAYMENT','PAID','REJECTED','RETURNED_FOR_CORRECTION','REVERSED')),
 total_earnings_piasters bigint not null default 0,total_deductions_piasters bigint not null default 0,net_pay_piasters bigint not null default 0,
 submitted_at timestamptz,submitted_by uuid references auth.users(id),hr_approved_at timestamptz,hr_approved_by uuid references auth.users(id),amany_approved_at timestamptz,amany_approved_by uuid references auth.users(id),
 locked_at timestamptz,rejection_reason text,journal_entry_id uuid references public.journal_entries(id),reversal_of uuid references public.payroll_runs(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),unique(payroll_month,division)
);
create table public.payroll_lines(
 id uuid primary key default gen_random_uuid(),payroll_run_id uuid not null references public.payroll_runs(id),employee_id uuid not null references public.hr_employees(id),employee_code_snapshot text not null,employee_name_snapshot text not null,
 basic_piasters bigint not null default 0,fixed_allowances_piasters bigint not null default 0,transport_allowance_piasters bigint not null default 0,housing_allowance_piasters bigint not null default 0,overtime_piasters bigint not null default 0,cover_piasters bigint not null default 0,bonuses_piasters bigint not null default 0,commissions_piasters bigint not null default 0,
 absence_piasters bigint not null default 0,late_piasters bigint not null default 0,early_leave_piasters bigint not null default 0,unpaid_leave_piasters bigint not null default 0,penalties_piasters bigint not null default 0,loan_installments_piasters bigint not null default 0,insurance_piasters bigint not null default 0,tax_piasters bigint not null default 0,other_deductions_piasters bigint not null default 0,
 total_earnings_piasters bigint generated always as (basic_piasters+fixed_allowances_piasters+transport_allowance_piasters+housing_allowance_piasters+overtime_piasters+cover_piasters+bonuses_piasters+commissions_piasters) stored,
 total_deductions_piasters bigint generated always as (absence_piasters+late_piasters+early_leave_piasters+unpaid_leave_piasters+penalties_piasters+loan_installments_piasters+insurance_piasters+tax_piasters+other_deductions_piasters) stored,
 net_pay_piasters bigint generated always as ((basic_piasters+fixed_allowances_piasters+transport_allowance_piasters+housing_allowance_piasters+overtime_piasters+cover_piasters+bonuses_piasters+commissions_piasters)-(absence_piasters+late_piasters+early_leave_piasters+unpaid_leave_piasters+penalties_piasters+loan_installments_piasters+insurance_piasters+tax_piasters+other_deductions_piasters)) stored,
 notes text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),unique(payroll_run_id,employee_id)
);
create table public.payroll_payments(id uuid primary key default gen_random_uuid(),payroll_run_id uuid not null unique references public.payroll_runs(id),payment_date date not null,payment_method text not null check(payment_method in ('CASH','BANK')),payment_reference text not null,document_url text not null,amount_piasters bigint not null check(amount_piasters>0),journal_entry_id uuid references public.journal_entries(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_import_batches(id uuid primary key default gen_random_uuid(),file_name text not null,sha256 text,preview_rows integer not null default 0,valid_rows integer not null default 0,duplicate_rows integer not null default 0,status text not null default 'PREVIEW_ONLY',validation_result jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create table public.hr_audit_events(id bigint generated always as identity primary key,table_name text not null,record_id text,action text not null,old_data jsonb,new_data jsonb,changed_at timestamptz not null default now(),changed_by uuid references auth.users(id));

create or replace function public.is_hr_authority(p_stage text) returns boolean language sql stable security invoker set search_path='public','pg_temp' as $$select exists(select 1 from public.hr_approval_authorities where stage=p_stage and active and authority_user_id=auth.uid())$$;
create or replace function public.can_view_hr_payroll() returns boolean language sql stable security invoker set search_path='public','pg_temp' as $$select public.current_finance_role() in ('OWNER','HR_MANAGER','HR_OFFICER','PAYROLL_CASHIER','DR_AMANY_APPROVER')$$;

alter table public.hr_approval_authorities enable row level security;alter table public.hr_employees enable row level security;alter table public.hr_employee_documents enable row level security;alter table public.hr_attendance enable row level security;alter table public.hr_leave_requests enable row level security;alter table public.hr_cover_assignments enable row level security;alter table public.hr_compensation_items enable row level security;alter table public.hr_employee_loans enable row level security;alter table public.hr_employee_requests enable row level security;alter table public.hr_applicants enable row level security;alter table public.hr_onboarding_tasks enable row level security;alter table public.hr_performance_reviews enable row level security;alter table public.hr_training_records enable row level security;alter table public.hr_grievances enable row level security;alter table public.hr_custody_clearance enable row level security;alter table public.hr_terminations enable row level security;alter table public.payroll_runs enable row level security;alter table public.payroll_lines enable row level security;alter table public.payroll_payments enable row level security;alter table public.hr_import_batches enable row level security;alter table public.hr_audit_events enable row level security;

revoke all on public.hr_approval_authorities,public.hr_employees,public.hr_employee_documents,public.hr_attendance,public.hr_leave_requests,public.hr_cover_assignments,public.hr_compensation_items,public.hr_employee_loans,public.hr_employee_requests,public.hr_applicants,public.hr_onboarding_tasks,public.hr_performance_reviews,public.hr_training_records,public.hr_grievances,public.hr_custody_clearance,public.hr_terminations,public.payroll_runs,public.payroll_lines,public.payroll_payments,public.hr_import_batches,public.hr_audit_events from anon,authenticated;
grant select on public.hr_approval_authorities,public.hr_employees,public.hr_employee_documents,public.hr_attendance,public.hr_leave_requests,public.hr_cover_assignments,public.hr_compensation_items,public.hr_employee_loans,public.hr_employee_requests,public.hr_applicants,public.hr_onboarding_tasks,public.hr_performance_reviews,public.hr_training_records,public.hr_grievances,public.hr_custody_clearance,public.hr_terminations,public.payroll_runs,public.payroll_lines,public.payroll_payments,public.hr_import_batches,public.hr_audit_events to authenticated;
grant insert,update on public.hr_employees,public.hr_employee_documents,public.hr_attendance,public.hr_leave_requests,public.hr_cover_assignments,public.hr_compensation_items,public.hr_employee_loans,public.hr_employee_requests,public.hr_applicants,public.hr_onboarding_tasks,public.hr_performance_reviews,public.hr_training_records,public.hr_grievances,public.hr_custody_clearance,public.hr_terminations,public.payroll_runs,public.payroll_lines,public.hr_import_batches to authenticated;

create policy hr_authorities_read on public.hr_approval_authorities for select to authenticated using(public.current_finance_role() in ('OWNER','HR_MANAGER','HR_OFFICER','PAYROLL_CASHIER','DR_AMANY_APPROVER'));
create policy hr_employees_read on public.hr_employees for select to authenticated using(public.current_finance_role() in ('OWNER','HR_MANAGER','HR_OFFICER'));
create policy hr_employees_write on public.hr_employees for all to authenticated using(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER')) with check(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER'));

do $$declare t text;begin foreach t in array array['hr_employee_documents','hr_attendance','hr_leave_requests','hr_cover_assignments','hr_compensation_items','hr_employee_loans','hr_employee_requests','hr_applicants','hr_onboarding_tasks','hr_performance_reviews','hr_training_records','hr_grievances','hr_custody_clearance','hr_terminations','hr_import_batches'] loop execute format('create policy %I on public.%I for select to authenticated using(public.current_finance_role() in (''OWNER'',''HR_MANAGER'',''HR_OFFICER''))',t||'_read',t);execute format('create policy %I on public.%I for insert to authenticated with check(public.current_finance_role() in (''HR_MANAGER'',''HR_OFFICER''))',t||'_insert',t);execute format('create policy %I on public.%I for update to authenticated using(public.current_finance_role() in (''HR_MANAGER'',''HR_OFFICER'')) with check(public.current_finance_role() in (''HR_MANAGER'',''HR_OFFICER''))',t||'_update',t);end loop;end$$;
create policy payroll_runs_read on public.payroll_runs for select to authenticated using(public.can_view_hr_payroll() and (public.current_finance_role()<>'PAYROLL_CASHIER' or status in ('AMANY_APPROVED','READY_FOR_PAYMENT','PAID')));
create policy payroll_runs_insert on public.payroll_runs for insert to authenticated with check(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER') and status='DRAFT' and created_by=auth.uid());
create policy payroll_runs_update_draft on public.payroll_runs for update to authenticated using(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER') and status in ('DRAFT','RETURNED_FOR_CORRECTION')) with check(status in ('DRAFT','RETURNED_FOR_CORRECTION'));
create policy payroll_lines_read on public.payroll_lines for select to authenticated using(exists(select 1 from public.payroll_runs r where r.id=payroll_run_id and public.can_view_hr_payroll() and (public.current_finance_role()<>'PAYROLL_CASHIER' or r.status in ('AMANY_APPROVED','READY_FOR_PAYMENT','PAID'))));
create policy payroll_lines_write on public.payroll_lines for all to authenticated using(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER') and exists(select 1 from public.payroll_runs r where r.id=payroll_run_id and r.status in ('DRAFT','RETURNED_FOR_CORRECTION'))) with check(public.current_finance_role() in ('HR_MANAGER','HR_OFFICER') and exists(select 1 from public.payroll_runs r where r.id=payroll_run_id and r.status in ('DRAFT','RETURNED_FOR_CORRECTION')));
create policy payroll_payments_read on public.payroll_payments for select to authenticated using(public.current_finance_role() in ('OWNER','HR_MANAGER','DR_AMANY_APPROVER','PAYROLL_CASHIER'));
create policy hr_audit_read on public.hr_audit_events for select to authenticated using(public.current_finance_role() in ('OWNER','HR_MANAGER','DR_AMANY_APPROVER'));

create or replace function private.hr_recalc_run(p_run uuid) returns void language sql security definer set search_path='' as $$update public.payroll_runs r set total_earnings_piasters=x.e,total_deductions_piasters=x.d,net_pay_piasters=x.n,updated_at=now() from(select coalesce(sum(total_earnings_piasters),0)e,coalesce(sum(total_deductions_piasters),0)d,coalesce(sum(net_pay_piasters),0)n from public.payroll_lines where payroll_run_id=p_run)x where r.id=p_run$$;
create or replace function private.hr_audit(p_table text,p_id uuid,p_action text,p_old jsonb,p_new jsonb) returns void language sql security definer set search_path='' as $$insert into public.hr_audit_events(table_name,record_id,action,old_data,new_data,changed_by)values(p_table,p_id::text,p_action,p_old,p_new,auth.uid())$$;
create or replace function private.hr_guard_run() returns trigger language plpgsql security definer set search_path='' as $$begin if tg_op='DELETE' and old.status not in ('DRAFT','RETURNED_FOR_CORRECTION') then raise exception 'Approved payroll cannot be deleted';end if;if tg_op='UPDATE' and new.status is distinct from old.status and current_setting('bradford.hr_workflow',true)<>'1' then raise exception 'Use HR payroll workflow actions';end if;return coalesce(new,old);end$$;
create trigger hr_guard_payroll_run before update or delete on public.payroll_runs for each row execute function private.hr_guard_run();
create or replace function private.hr_line_change() returns trigger language plpgsql security definer set search_path='' as $$declare rid uuid:=coalesce(new.payroll_run_id,old.payroll_run_id);begin if not exists(select 1 from public.payroll_runs where id=rid and status in ('DRAFT','RETURNED_FOR_CORRECTION')) then raise exception 'Payroll lines are locked';end if;perform private.hr_recalc_run(rid);return coalesce(new,old);end$$;
create trigger hr_line_recalc after insert or update or delete on public.payroll_lines for each row execute function private.hr_line_change();
create or replace function private.hr_line_snapshot() returns trigger language plpgsql security definer set search_path='' as $$begin select employee_code,full_name into new.employee_code_snapshot,new.employee_name_snapshot from public.hr_employees where id=new.employee_id;if new.employee_code_snapshot is null then raise exception 'Employee not found';end if;return new;end$$;
create trigger hr_line_snapshot before insert on public.payroll_lines for each row execute function private.hr_line_snapshot();

create or replace function private.hr_post_journal(p_run uuid,p_kind text,p_payment_method text default null) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare r public.payroll_runs%rowtype; jid uuid; cash_code text;
begin
 select * into r from public.payroll_runs where id=p_run;
 if not found or r.net_pay_piasters<=0 then raise exception 'Payroll net amount must be positive';end if;
 if p_kind='ACCRUAL' then
  insert into public.journal_entries(transaction_date,description,source_module,source_id,status,created_by)values(r.payroll_month,'Payroll accrual '||to_char(r.payroll_month,'YYYY-MM'),'payroll_runs',r.id,'DRAFT',auth.uid())returning id into jid;
  insert into public.journal_lines(entry_id,line_no,account_code,debit_piasters,credit_piasters,description,cost_center_id)values(jid,1,'5100',r.net_pay_piasters,0,'Payroll expense',r.cost_center_id),(jid,2,'2400',0,r.net_pay_piasters,'Payroll payable',r.cost_center_id);
 elsif p_kind='PAYMENT' then
  cash_code:=case when p_payment_method='CASH' then '1100' else '1200' end;
  insert into public.journal_entries(transaction_date,description,source_module,source_id,status,created_by)values(current_date,'Payroll payment '||to_char(r.payroll_month,'YYYY-MM'),'payroll_payments',r.id,'DRAFT',auth.uid())returning id into jid;
  insert into public.journal_lines(entry_id,line_no,account_code,debit_piasters,credit_piasters,description,cost_center_id)values(jid,1,'2400',r.net_pay_piasters,0,'Settle payroll payable',r.cost_center_id),(jid,2,cash_code,0,r.net_pay_piasters,'Payroll payment',r.cost_center_id);
 else raise exception 'Unsupported payroll journal kind';end if;
 perform set_config('bradford.workflow','1',true);update public.journal_entries set status='POSTED',posted_at=now(),posted_by=auth.uid() where id=jid;
 return jid;
end$$;

create or replace function public.hr_payroll_action(p_run uuid,p_action text,p_reason text default null) returns void language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare r public.payroll_runs%rowtype; target text;begin
 if auth.uid() is null then raise exception 'Authentication required';end if;select * into r from public.payroll_runs where id=p_run for update;if not found then raise exception 'Payroll run not found';end if;
 if p_action='SUBMIT' and r.status in ('DRAFT','RETURNED_FOR_CORRECTION') and public.current_finance_role() in ('HR_OFFICER','HR_MANAGER') then target:='SUBMITTED_TO_HR_MANAGER';
 elsif p_action='HR_APPROVE' and r.status='SUBMITTED_TO_HR_MANAGER' and public.is_hr_authority('HR_MANAGER') then target:='HR_MANAGER_APPROVED';
 elsif p_action='RETURN' and r.status in ('SUBMITTED_TO_HR_MANAGER','HR_MANAGER_APPROVED') and public.is_hr_authority('HR_MANAGER') then if length(btrim(coalesce(p_reason,'')))<3 then raise exception 'Reason required';end if;target:='RETURNED_FOR_CORRECTION';
 elsif p_action='AMANY_APPROVE' and r.status='HR_MANAGER_APPROVED' and public.is_hr_authority('AMANY_FINAL') then target:='AMANY_APPROVED';
 elsif p_action='REJECT' and r.status='HR_MANAGER_APPROVED' and public.is_hr_authority('AMANY_FINAL') then if length(btrim(coalesce(p_reason,'')))<3 then raise exception 'Reason required';end if;target:='REJECTED';
 else raise exception 'Not authorized or invalid payroll transition';end if;
 perform set_config('bradford.hr_workflow','1',true);
 update public.payroll_runs set status=target,submitted_at=case when target='SUBMITTED_TO_HR_MANAGER' then now() else submitted_at end,submitted_by=case when target='SUBMITTED_TO_HR_MANAGER' then auth.uid() else submitted_by end,hr_approved_at=case when target='HR_MANAGER_APPROVED' then now() else hr_approved_at end,hr_approved_by=case when target='HR_MANAGER_APPROVED' then auth.uid() else hr_approved_by end,amany_approved_at=case when target='AMANY_APPROVED' then now() else amany_approved_at end,amany_approved_by=case when target='AMANY_APPROVED' then auth.uid() else amany_approved_by end,locked_at=case when target='AMANY_APPROVED' then now() else locked_at end,rejection_reason=p_reason,updated_at=now(),updated_by=auth.uid() where id=p_run;
 if target='AMANY_APPROVED' then update public.payroll_runs set journal_entry_id=private.hr_post_journal(p_run,'ACCRUAL'),status='READY_FOR_PAYMENT' where id=p_run;end if;
 perform private.hr_audit('payroll_runs',p_run,p_action,to_jsonb(r),jsonb_build_object('status',target,'reason',p_reason));
end$$;

create or replace function public.hr_record_payroll_payment(p_run uuid,p_date date,p_method text,p_reference text,p_document_url text) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$declare r public.payroll_runs%rowtype;pid uuid;jid uuid;begin
 if not public.is_hr_authority('PAYMENT') then raise exception 'Only designated payroll cashier can record payment';end if;select * into r from public.payroll_runs where id=p_run for update;if r.status not in ('AMANY_APPROVED','READY_FOR_PAYMENT') then raise exception 'Payroll is not approved for payment';end if;if p_method not in ('CASH','BANK') or nullif(btrim(p_reference),'') is null or nullif(btrim(p_document_url),'') is null then raise exception 'Payment method, reference and document are required';end if;
 jid:=private.hr_post_journal(p_run,'PAYMENT',p_method);insert into public.payroll_payments(payroll_run_id,payment_date,payment_method,payment_reference,document_url,amount_piasters,journal_entry_id,created_by)values(p_run,p_date,p_method,btrim(p_reference),btrim(p_document_url),r.net_pay_piasters,jid,auth.uid())returning id into pid;
 perform set_config('bradford.hr_workflow','1',true);update public.payroll_runs set status='PAID',locked_at=now(),updated_at=now(),updated_by=auth.uid() where id=p_run;perform private.hr_audit('payroll_payments',pid,'PAY',null,jsonb_build_object('run_id',p_run,'amount',r.net_pay_piasters,'method',p_method,'reference',p_reference));return pid;end$$;

revoke all on function private.hr_recalc_run(uuid),private.hr_audit(text,uuid,text,jsonb,jsonb),private.hr_guard_run(),private.hr_line_change(),private.hr_line_snapshot(),private.hr_post_journal(uuid,text,text) from public,anon,authenticated;
revoke all on function public.hr_payroll_action(uuid,text,text),public.hr_record_payroll_payment(uuid,date,text,text,text) from public,anon;grant execute on function public.hr_payroll_action(uuid,text,text),public.hr_record_payroll_payment(uuid,date,text,text,text) to authenticated;
create index hr_employees_search_idx on public.hr_employees(employee_code,full_name,status);create index hr_docs_expiry_idx on public.hr_employee_documents(expiry_date);create index hr_attendance_date_idx on public.hr_attendance(work_date,employee_id);create index payroll_runs_month_idx on public.payroll_runs(payroll_month,status);create index payroll_lines_run_idx on public.payroll_lines(payroll_run_id,employee_id);
commit;
