-- Phase 2: additive procurement/vendor controls. No seed data and no existing financial row updates.
alter table public.vendors add column if not exists vendor_code text;
alter table public.vendors add column if not exists legal_name text;
alter table public.vendors add column if not exists commercial_name text;
alter table public.vendors add column if not exists commercial_register text;
alter table public.vendors add column if not exists address text;
alter table public.vendors add column if not exists category text;
alter table public.vendors add column if not exists suspended_reason text;
alter table public.vendors add column if not exists rating numeric check(rating between 0 and 5);
create unique index if not exists vendors_vendor_code_uq on public.vendors(vendor_code) where vendor_code is not null;
create unique index if not exists vendors_tax_id_uq on public.vendors(lower(btrim(tax_id))) where tax_id is not null;
create sequence if not exists public.vendor_code_seq;

create table if not exists public.procurement_rfqs(id uuid primary key default gen_random_uuid(),rfq_number text not null unique,requisition_id uuid not null references public.purchase_requisitions(id),status text not null default 'DRAFT' check(status in('DRAFT','ISSUED','CLOSED','CANCELLED')),response_due_at timestamptz,required_quote_count integer not null default 3 check(required_quote_count>=1),exception_reason text,exception_document_url text,exception_approved_at timestamptz,exception_approved_by uuid references auth.users(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table if not exists public.procurement_rfq_vendors(rfq_id uuid not null references public.procurement_rfqs(id),vendor_id uuid not null references public.vendors(id),invited_at timestamptz not null default now(),primary key(rfq_id,vendor_id));
alter table public.vendor_quotations add column if not exists rfq_id uuid references public.procurement_rfqs(id);
alter table public.vendor_quotations add column if not exists quality_score numeric check(quality_score between 0 and 100);
alter table public.vendor_quotations add column if not exists delivery_days integer check(delivery_days>=0);
alter table public.vendor_quotations add column if not exists evaluation_note text;
alter table public.vendor_quotations add column if not exists status text not null default 'DRAFT' check(status in('DRAFT','SUBMITTED','SELECTED','REJECTED','WITHDRAWN'));

create table if not exists public.procurement_approval_limits(id uuid primary key default gen_random_uuid(),stage text not null,role public.finance_role not null,min_piasters bigint not null default 0,max_piasters bigint,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid references auth.users(id),check(max_piasters is null or max_piasters>=min_piasters),unique(stage,role,min_piasters));
create table if not exists public.procurement_quote_decisions(id uuid primary key default gen_random_uuid(),rfq_id uuid not null references public.procurement_rfqs(id),selected_quotation_id uuid not null references public.vendor_quotations(id),comparison jsonb not null,decision_reason text not null,three_quotes_met boolean not null,exception_reason text,approved_at timestamptz not null default now(),approved_by uuid not null references auth.users(id),unique(rfq_id));
create table if not exists public.purchase_returns(id uuid primary key default gen_random_uuid(),return_number text not null unique,goods_receipt_id uuid not null references public.goods_receipts(id),vendor_id uuid not null references public.vendors(id),return_date date not null,status text not null default 'DRAFT' check(status in('DRAFT','SUBMITTED','POSTED','REJECTED','REVERSED')),reason text not null,document_urls text[] not null default '{}',journal_entry_id uuid references public.journal_entries(id),created_at timestamptz not null default now(),created_by uuid references auth.users(id),posted_at timestamptz,posted_by uuid references auth.users(id));
create table if not exists public.purchase_return_lines(id uuid primary key default gen_random_uuid(),purchase_return_id uuid not null references public.purchase_returns(id),goods_receipt_line_id uuid not null references public.goods_receipt_lines(id),quantity numeric not null check(quantity>0),unit_cost_piasters bigint not null check(unit_cost_piasters>=0),line_total_piasters bigint generated always as ((quantity*unit_cost_piasters)::bigint) stored,unique(purchase_return_id,goods_receipt_line_id));
create table if not exists public.procurement_match_results(id uuid primary key default gen_random_uuid(),vendor_bill_id uuid not null unique references public.vendor_bills(id),po_total_piasters bigint not null,received_total_piasters bigint not null,invoice_total_piasters bigint not null,quantity_variance numeric not null default 0,amount_variance_piasters bigint not null default 0,result text not null check(result in('MATCHED','VARIANCE','NEEDS_REVIEW')),checked_at timestamptz not null default now(),checked_by uuid not null references auth.users(id),details jsonb not null default '{}');

drop policy if exists vendors_write on public.vendors;
create policy vendors_write_authenticated on public.vendors for all to authenticated using(public.current_finance_role() in('OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT')) with check(public.current_finance_role() in('OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT'));
drop policy if exists vendor_quotes_write on public.vendor_quotations;
create policy vendor_quotes_draft_write on public.vendor_quotations for all to authenticated using(public.current_finance_role() in('OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT') and status='DRAFT') with check(public.current_finance_role() in('OWNER','CEO','FINANCE_MANAGER','ACCOUNTANT') and status='DRAFT');

do $$declare t text;begin foreach t in array array['procurement_rfqs','procurement_rfq_vendors','procurement_approval_limits','procurement_quote_decisions','purchase_returns','purchase_return_lines','procurement_match_results'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('create policy %I on public.%I for select to authenticated using(public.current_finance_role() in (''OWNER'',''CEO'',''FINANCE_MANAGER'',''ACCOUNTANT'',''AUDITOR''))',t||'_read',t);end loop;end$$;
grant insert,update on public.procurement_rfqs,public.procurement_rfq_vendors,public.purchase_returns,public.purchase_return_lines to authenticated;
create policy rfq_draft_write on public.procurement_rfqs for all to authenticated using(status='DRAFT' and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT')) with check(status='DRAFT' and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT'));
create policy rfq_vendor_write on public.procurement_rfq_vendors for all to authenticated using(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT') and exists(select 1 from public.procurement_rfqs r where r.id=rfq_id and r.status='DRAFT')) with check(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT') and exists(select 1 from public.procurement_rfqs r where r.id=rfq_id and r.status='DRAFT'));
create policy purchase_return_draft_write on public.purchase_returns for all to authenticated using(status='DRAFT' and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT')) with check(status='DRAFT' and public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT'));
create policy purchase_return_lines_draft_write on public.purchase_return_lines for all to authenticated using(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT') and exists(select 1 from public.purchase_returns r where r.id=purchase_return_id and r.status='DRAFT')) with check(public.current_finance_role() in('OWNER','FINANCE_MANAGER','ACCOUNTANT') and exists(select 1 from public.purchase_returns r where r.id=purchase_return_id and r.status='DRAFT'));

create or replace function public.procurement_three_way_match(p_bill uuid) returns text language plpgsql security definer set search_path='public','private','pg_temp' as $$declare b public.vendor_bills%rowtype;po_total bigint;received_total bigint;result text;begin if public.current_finance_role() not in('OWNER','FINANCE_MANAGER','ACCOUNTANT','AUDITOR') then raise exception 'Not authorized';end if;select * into b from public.vendor_bills where id=p_bill for update;if not found or b.purchase_order_id is null or b.goods_receipt_id is null then raise exception 'PO and receiving note are required';end if;select total_piasters into po_total from public.purchase_orders where id=b.purchase_order_id;select coalesce(sum(grl.quantity_received*pol.unit_cost_piasters),0)::bigint into received_total from public.goods_receipt_lines grl join public.purchase_order_lines pol on pol.id=grl.purchase_order_line_id where grl.goods_receipt_id=b.goods_receipt_id and pol.purchase_order_id=b.purchase_order_id;result:=case when b.total_piasters=po_total and b.total_piasters=received_total then 'MATCHED' else 'VARIANCE' end;insert into public.procurement_match_results(vendor_bill_id,po_total_piasters,received_total_piasters,invoice_total_piasters,amount_variance_piasters,result,checked_by,details)values(b.id,po_total,received_total,b.total_piasters,b.total_piasters-received_total,result,auth.uid(),jsonb_build_object('po',b.purchase_order_id,'grn',b.goods_receipt_id)) on conflict(vendor_bill_id) do update set po_total_piasters=excluded.po_total_piasters,received_total_piasters=excluded.received_total_piasters,invoice_total_piasters=excluded.invoice_total_piasters,amount_variance_piasters=excluded.amount_variance_piasters,result=excluded.result,checked_at=now(),checked_by=auth.uid(),details=excluded.details;update public.vendor_bills set match_status=result where id=b.id and status='DRAFT';insert into public.audit_events(table_name,record_id,action,new_data,changed_by)values('vendor_bills',b.id::text,'THREE_WAY_MATCH',jsonb_build_object('result',result,'po_total',po_total,'received_total',received_total,'invoice_total',b.total_piasters),auth.uid());return result;end$$;
revoke all on function public.procurement_three_way_match(uuid) from public,anon;grant execute on function public.procurement_three_way_match(uuid) to authenticated;

create or replace function private.guard_vendor_payment() returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$declare s text;m text;begin select status,match_status into s,m from public.vendor_bills where id=new.vendor_bill_id;if s not in('POSTED','PARTIALLY_PAID') or m not in('MATCHED','EXCEPTION_APPROVED') then raise exception 'Vendor bill must be POSTED and matched before payment';end if;if exists(select 1 from public.vendor_payments p where p.vendor_bill_id=new.vendor_bill_id and p.status in('DRAFT','SUBMITTED','POSTED') and p.amount_piasters=new.amount_piasters and p.payment_date=new.payment_date and p.effect_sign=1) then raise exception 'Possible duplicate vendor payment';end if;return new;end$$;
drop trigger if exists vendor_payment_guard on public.vendor_payments;create trigger vendor_payment_guard before insert on public.vendor_payments for each row execute function private.guard_vendor_payment();
revoke all on function private.guard_vendor_payment() from public,anon,authenticated;
